/**
* Copyright (c) 2024 Rainbow Robotics
* Use of this source code is governed by the Apache 2.0, see LICENSE
*/

#pragma once

#include <map>
#include <string>

namespace rb::podo {

struct Message {
  std::string ko;
  std::string en;
};

inline std::map<int, Message> ErrorCodeMessage = {
{ 0, {R"(로봇 팔의 전원이 꺼졌습니다. 다시 사용하려면 활성화를 수행하세요.)", R"(Power Down Detected. Re-initialize the robot!)"} },
{ 1, {R"(컨베이어 트래킹을 함께 수행하기에는 설정된 동작 속도가 너무 빠릅니다.)", R"(Too Fast motion for Conveyor tracking!)"} },
{ 2, {R"(자동 TCP 회전 정렬 기능을 사용할 수 있는 범주가 아닙니다.)", R"(Condition fail for TCP orientation auto-alignment)"} },
{ 3, {R"(프로그램이 충돌감지로 인해 종료되었습니다.)", R"(Program is Stopped because of Collision-Detection)"} },
{ 4, {R"(위빙 연산 오류 (type: AMP))", R"(Weaving path calculation Fail (type: AMP))"} },
{ 5, {R"(위빙 연산 오류 (type: VEL))", R"(Weaving path calculation Fail (type: VEL))"} },
{ 6, {R"(위빙 연산 오류 (type: TPA))", R"(Weaving path calculation Fail (type: TPA))"} },
{ 7, {R"(위빙 연산 오류 (type: DRG))", R"(Weaving path calculation Fail (type: DRG))"} },
{ 8, {R"(위빙 연산 오류 (type: OFF))", R"(Weaving path calculation Fail (type: OFF))"} },
{ 9, {R"(위빙 연산 오류 (type: SCA))", R"(Weaving path calculation Fail (type: SCA))"} },
{ 10, {R"(위빙 연산 오류 (type: UND))", R"(Weaving path calculation Fail (type: UND))"} },
{ 11, {R"(위빙 설정 오류 : 허용되지 않는 명령어 입니다.)", R"(Weaving Setting Error: Cannot run this Command)"} },
{ 12, {R"(위빙 설정 오류 : 진폭 설정이 허용 범위 밖 입니다.)", R"(Weaving Setting Error: Out of bounds (amplitude))"} },
{ 13, {R"(위빙 설정 오류 : 속도 설정이 허용 범위 밖 입니다.)", R"(Weaving Setting Error: Out of bounds (velocity))"} },
{ 14, {R"(위빙 설정 오류 : 시간 설정이 허용 범위 밖 입니다.)", R"(Weaving Setting Error: Out of bounds (time))"} },
{ 15, {R"(위빙 설정 오류 : 왜곡률 설정이 허용 범위 밖 입니다.)", R"(Weaving Setting Error: Out of bounds (distortion rate))"} },
{ 16, {R"(위빙 설정 오류 : 두 셋 포인트가 너무 가깝습니다.)", R"(Weaving Setting Error: Set-points are too close)"} },
{ 17, {R"(브레이크가 해제되었습니다. 선택된 관절이 풀렸는지 확인하세요 !)", R"(Brake is opened. Check the selected joint is released !)"} },
{ 18, {R"(선택된 관절 초기화를 수행하였습니다. 전체 시스템을 재부팅하세요 !)", R"(Selected Joint is Initialized. Reboot All system !)"} },
{ 19, {R"(조그버튼 설정 가져오기 실패 (범주를 넘었습니다))", R"(Jog Button Get Info Fail (Out of index bound))"} },
{ 20, {R"(조그버튼 설정 변경하기 실패 (범주를 넘었습니다))", R"(Jog Button Set Info Fail (Out of bound))"} },
{ 21, {R"(패턴 내부 카운트가 범주를 넘어갑니다.)", R"(Pattern internal count is over its bound)"} },
{ 22, {R"(제어박스 내부 파일이 이 경로로 복사되었습니다. \n(TabletStorage/Android/data/com.rainbow.cobot/files/CopyFrom_ControlBox))", R"(Control Box Files are copied into \n(TabletStorage/Android/data/com.rainbow.cobot/files/CopyFrom_ControlBox))"} },
{ 23, {R"(소프트웨어 업데이트 실패 (타입 1) \nUI프로그램이 정식버전 인지 확인하세요\n재시도를 권장합니다)", R"(Software Update Fail (type 1)\nCheck whether the UI App program is full-version\nPlease try again)"} },
{ 24, {R"(소프트웨어 업데이트 실패 (타입 2) \n내부 파일복사 기능 문제 발생\n재시도를 권장합니다)", R"(Software Update Fail (type 2)\nInternal files copy failure\nPlease try again)"} },
{ 25, {R"(소프트웨어 업데이트 실패 (타입 3) \n시스템 파일 체크 문제 발생\n재시도를 권장합니다)", R"(Software Update Fail (type 1)\nFile system checking failure\nPlease try again)"} },
{ 26, {R"(소프트웨어 업데이트가 정상적으로 끝났습니다 ! \n시스템이 자동으로 재시작됩니다 \nPlease Wait...)", R"(Software Update Success !!!\nSystem will be re-boot automatically\nPlease Wait...)"} },
{ 27, {R"(호출된 저장 모션이 존재하지 않습니다.)", R"(Saved motion called does not exist.)"} },
{ 28, {R"(문법오류 : 녹화 모션 재생)", R"(Grammer Error : Recorded Path Run)"} },
{ 29, {R"(지원하지 않는 회전 옵션 입니다.)", R"(Selected Orientation option is not supported)"} },
{ 30, {R"(MoveJB 에러 : 명령어 수행 불가능 구간에서 동작이 호출됩니다.)", R"(MoveJB Error : Command can not be executed)"} },
{ 31, {R"(MoveJB 에러 : 동작을 수행하기에 불가능한 포인트 개수 입니다.)", R"(MoveJB Error : Too Low Point number)"} },
{ 32, {R"(MoveJB 에러 : 범주를 벗어나는 포인트가 존재합니다.)", R"(MoveJB Error : Joint Limit over)"} },
{ 33, {R"(MoveJB 에러 : 오프셋 설정이 불가능한 점이 존재합니다.)", R"(MoveJB Error : Imposible to adjust Set-Offset)"} },
{ 34, {R"(MoveJB 에러 : 너무 낮은 가속도가 설정되어 있습니다.)", R"(MoveJB Error : Too Low Acceleration is set)"} },
{ 35, {R"(MoveJB 에러 : 정의되지 않음)", R"(MoveJB Error : N/D)"} },
{ 36, {R"(MoveJB 에러 : 정의되지 않음)", R"(MoveJB Error : N/D)"} },
{ 37, {R"(MoveJB 에러 : 정의되지 않음)", R"(MoveJB Error : N/D)"} },
{ 38, {R"(조이스틱 연결에 성공하였습니다.)", R"(Joy-Stick is connected)"} },
{ 39, {R"(조이스틱 연결에 실패하였습니다.)", R"(Joy-Stick is not connected !!)"} },
{ 40, {R"(잘못된 암호를 입력하였습니다.)", R"(Wrong Password !!!)"} },
{ 41, {R"(모든 설정이 초기화되었습니다.\n시스템을 재부팅하세요.)", R"(All Settings are initialized.\nRe-boot All systems)"} },
{ 42, {R"(저장이 완료되었습니다.)", R"(Save Done !)"} },
{ 43, {R"(앞선 과정을 먼저 수행해야 합니다.)", R"(Do previous procedure first !!!)"} },
{ 44, {R"(연산 오류가 발생하였습니다.)", R"(Calculation Error !!!)"} },
{ 45, {R"(명령어 수행이 불가합니다.\n동작 또는 프로그램이 실행중입니다.)", R"(Cannot run this command.\nOther motion or program is running!)"} },
{ 46, {R"(로봇이 활성화되어 있습니다. \n로봇을 먼저 비활성화 (끄기)하고 이 명령을 수행하세요.)", R"(Robot is Activated !! \nDe-activate robot first.)"} },
{ 47, {R"(잘못된 제어기 번호 입력입니다.)", R"(Wrong BNO (Board Number) input !!!)"} },
{ 48, {R"(입력된 파라미터가 지원 범주를 벗어납니다.)", R"(Input Parameters are out-of bound !!!)"} },
{ 49, {R"(CAN 데이터 읽기 시간초과 오류)", R"(CAN Data Read Time-out !!!)"} },
{ 50, {R"(잘못된 모델 코드 번호를 넣었습니다.)", R"(Wrong Model-Key number !!!)"} },
{ 51, {R"(제어 게인이 변경되었습니다.\n원하는 값으로 변경되었는지 꼭 재확인하세요 !!!)", R"(Control Gains are changed !!!\nPlease double check !!!!)"} },
{ 52, {R"(지원 가능한 최대 Thread (쓰레드) 개수를 넘어 섭니다.)", R"(Exceeds the maximum number of Threads that can be supported.)"} },
{ 53, {R"(서브 프로그램 (Sub.P)이 과도하게 다단계로 열렸습니다.)", R"(SubProgram called too deeply !!!)"} },
{ 54, {R"(서브 프로그램 (Sub.P)이 과도하게 많이 열렸습니다.)", R"(SubProgram called too much !!!)"} },
{ 55, {R"(브레이크가 열리고, DQ 정렬이 수행되었습니다.\n브레이크가 잘 열렸고, DQ 정렬이 잘 되었는지 확인하세요 !)", R"(Brake is opened & DQ alignment is performed.\nMake sure whether Brake is opend and DQ is well-aligned)"} },
{ 56, {R"(DQ Save (DQ 저장 완료) \nDQ 정렬이 잘 되었는지 확인하세요 !)", R"(DQ Save done !! \nMake sure whether DQ is well-aligned)"} },
{ 57, {R"(전류 센서 초기화 (nulling) 완료 :))", R"(Current Sensor Nulling done :))"} },
{ 58, {R"(제어박스 SMPS 오류\n선 연결 상태를 확인하세요.\n퓨즈가 나갔을 가능성이 있습니다.)", R"(Control Box SMPS Error\nCheck cable connection\nFuse may have been disconnected.)"} },
{ 59, {R"(제어박스 48V 스위치 오류\n제공되는 48V 스위치 단자대의 커넥터 여부를 확인하세요.)", R"(Control Box 48V Switch Error\nCheck whether the supplied 48V switch terminal block is connected.)"} },
{ 60, {R"(제어박스 디지털 인풋의 보호 정지 커넥터 (16/17포트) 를 확인하세요.)", R"(Control Box GP Switch Error\nCheck Protective stop connector (Din16/17))"} },
{ 61, {R"(제어박스 내부 파워 스위칭 오류\n문제가 지속되면 제조사에 문의하세요.)", R"(Control Box Power-switching Error\nIf the problem persists, contact the manufacturer.)"} },
{ 62, {R"(제어박스 내부 FET 스위치 오류\n문제가 지속되면 제조사에 문의하세요.)", R"(Control Box FET switching Error\nIf the problem persists, contact the manufacturer.)"} },
{ 63, {R"(비상 스위치 (EMO/EMG switch) 및 리셋 스위치를 확인하세요.)", R"(Check EMG (EMO) Switch or Reset Switch status)"} },
{ 64, {R"(제어박스와 로봇의 케이블 연결 여부를 다시 확인하세요.)", R"(Check Cable-connection (between Robot and ControlBox) status)"} },
{ 65, {R"(로봇 모터 제어기 연결 검사 오류)", R"(Robot Motor Controller connection check Fail)"} },
{ 66, {R"(로봇 툴 플랜지 보드 연결 검사 오류)", R"(Robot Tool Flange Board (TFB) connection check Fail)"} },
{ 67, {R"(로봇 툴 플랜지 데이터 연결 시간 초과)", R"(Robot Tool Flange DAQ time out)"} },
{ 68, {R"(제어박스 48 SMPS 오류\n선 연결 상태를 확인하세요.\n퓨즈가 나갔을 가능성이 있습니다.)", R"(Control Box 48 SMPS Error\nCheck cable connection\nFuse may have been disconnected.)"} },
{ 69, {R"(제어박스 24 SMPS 오류\n선 연결 상태를 확인하세요.\n퓨즈가 나갔을 가능성이 있습니다.)", R"(Control Box 24 SMPS Error\nCheck cable connection\nFuse may have been disconnected.)"} },
{ 70, {R"(제어박스 12 SMPS 오류\n선 연결 상태를 확인하세요.\n퓨즈가 나갔을 가능성이 있습니다.)", R"(Control Box 12 SMPS Error\nCheck cable connection\nFuse may have been disconnected.)"} },
{ 71, {R"(제어박스 5 SMPS 오류\n선 연결 상태를 확인하세요.\n퓨즈가 나갔을 가능성이 있습니다.)", R"(Control Box 5 SMPS Error\nCheck cable connection\nFuse may have been disconnected.)"} },
{ 72, {R"(제어박스 L2C 연결 오류\n제어 PC와 통신 인터페이스 사이 LAN 케이블을 확인하세요.)", R"(Control Box L2C Error\nCheck the LAN cable between the Control-PC and the communication-interface-board)"} },
{ 73, {R"(제어박스 SafetyMCU 연결 오류\n제조사에 문의하세요.)", R"(Control Box SafetyMCU connection error\nContact the manufacturer)"} },
{ 74, {R"(로봇 모터 제어기 보호정지: ID 오류 타입 101)", R"(Robot Arm motor Controller Protection: ID check error type 101)"} },
{ 75, {R"(로봇 모터 제어기 보호정지: ID 오류 타입 102)", R"(Robot Arm motor Controller Protection: ID check error type 102)"} },
{ 76, {R"(지원되지 않는 기능입니다.)", R"(Not supported Function)"} },
{ 77, {R"(지원되지 않는 기능입니다.\n펌웨어 업그레이드를 통해 사용가능합니다.\n제조사에 문의하세요.)", R"(Not supported Function\nAvailable after Firmware upgrad\nContact the manufacturer)"} },
{ 78, {R"(Laser Range Finder 데이터 획득 시간 초가)", R"(Laser Range Finder data time out)"} },
{ 79, {R"(Pulse 기능을 사용하려는 포트에 다른 특수 기능이 이미 존재합니다.)", R"(Another special function already exists on the port for which you want to use the pulse function.)"} },
{ 80, {R"(잘못된 세팅 값이 저장되어 있습니다.\n제조사를 연락하여 문제를 확인하세요.)", R"(Wrong setting values are saved.\nContact the manufacturer)"} },
{ 81, {R"(충돌 감지 동작 모드 : 일반 정지로 설정되어 있습니다.)", R"(Collision detection motion setting : General stop)"} },
{ 82, {R"(충돌 감지 동작 모드 : 회피 정지로 설정되어 있습니다.)", R"(Collision detection motion setting : Evasion stop)"} },
{ 83, {R"(충돌 감지 동작 모드 : N/A)", R"(Collision detection motion setting : N/A)"} },
{ 84, {R"(충돌 감지 동작 모드 : N/A)", R"(Collision detection motion setting : N/A)"} },
{ 85, {R"(RB5 정밀도 세팅이 변경되었습니다.\n시스템을 재부팅하세요\n모든 모션을 다시 만드세요.)", R"(RB5 Accuracy setting is changed\nRe-boot all system\nRe-make all motions !!!)"} },
{ 86, {R"(자동COG : 외부 F/T센서가 부착되어 있지 않습니다.)", R"(AutoCOG : External F/T sensor is not attached)"} },
{ 87, {R"(자동COG : 현재 자세가 저장되었습니다.)", R"(AutoCOG : Current posture is saved)"} },
{ 88, {R"(자동COG : 데이터 획득 개수가 부족합니다.)", R"(AutoCOG : More data should be saved)"} },
{ 89, {R"(자동COG : 데이터 획득 중간에 센서 마운팅이 변경되어, 계산 불가능합니다.)", R"(AutoCOG : Fail to calculate-mounting angle is changed during DAQ)"} },
{ 90, {R"(자동COG : 데이터 획득 중간에 센서 타입이 변경되어, 계산 불가능합니다.)", R"(AutoCOG : Fail to calculate-sensor type is changed during DAQ)"} },
{ 91, {R"(자동COG : 정의되지 않음)", R"(AutoCOG : N/A)"} },
{ 92, {R"(자동COG : 정의되지 않음)", R"(AutoCOG : N/A)"} },
{ 93, {R"(Robotiq FT : 선택된 축에 대해서 다시 초기화 (Nulling)을 수행하세요.)", R"(Robotiq FT : Try Nulling again about this axis !!!)"} },
{ 94, {R"(Robotiq FT : 선택된 축에 대해 초기화 (Nulling)을 수행하였습니다.)", R"(Robotiq FT : Ok- Nulling about selected axis)"} },
{ 95, {R"(Robotiq FT : 외부 F/T센서로 Robotiq FT300이 선택되었습니다.\n전체 시스템을 재부팅하세요.)", R"(Robotiq FT : FT300 is selected for the external F/T sensor.\nRe-boot all systems)"} },
{ 96, {R"(Robotiq FT : 정의되지 않음)", R"(Robotiq FT : N/A)"} },
{ 97, {R"(Robotiq FT : 정의되지 않음)", R"(Robotiq FT : N/A)"} },
{ 98, {R"(Robotiq FT : 정의되지 않음)", R"(Robotiq FT : N/A)"} },
{ 99, {R"(Conveyor : 엔코더가 연결되어있지 않습니다.)", R"(Conveyor : Encoder data is not detected)"} },
{ 100, {R"(Conveyor : 방향 (축) 설정 값이 올바르지 않습니다.)", R"(Conveyor : Direction (Axis) settings have problem)"} },
{ 101, {R"(Conveyor : 정의되지 않음)", R"(Conveyor : N/A)"} },
{ 102, {R"(Conveyor : 정의되지 않음)", R"(Conveyor : N/A)"} },
{ 103, {R"(Conveyor : 정의되지 않음)", R"(Conveyor : N/A)"} },
{ 104, {R"(Conveyor : 정의되지 않음)", R"(Conveyor : N/A)"} },
{ 105, {R"(Conveyor : 정의되지 않음)", R"(Conveyor : N/A)"} },
{ 106, {R"(EMS 상태 : 연산 불가능 지점\n- 현재 지점은 역기구학 연산이 불가능합니다.\n- 특이점/데드존과 너무 가까운 자세일 수 있습니다.\n- 설정된 동작 속도가 과도하게 빠를 수 있습니다.\n- 이를 피하도록 동작을 재생성하세요.)", R"(EMS Status : Unsorvable posture\n- Inverse kinematics calculation is not possible at this point.\n- It may be too close to the singularity / dead zone.\n- The set speed/acceleration may be excessively fast.\n- Require to re-generate the motion to avoid this condition.)"} },
{ 107, {R"(EMS 상태 : 기구학 연산 오류\n- 관성 좌표계 동작 도중 역기구학 연산 오류가 발생합니다.\n- 특이점/데드존과 너무 가까운 자세일 수 있습니다.\n- 설정된 동작 속도가 과도하게 빠를 수 있습니다.\n- 이를 피하도록 동작을 재생성하세요.)", R"(EMS Status : Inverse kinematics numeric error\n- Inverse kinematics calculation error during cartesian motion.\n- It may be too close to the singularity / dead zone.\n- The set speed/acceleration may be excessively fast.\n- Require to re-generate the motion to avoid this condition.)"} },
{ 108, {R"(EMS 상태 : 작업 가능 영역을 벗어납니다.\n- 관성 좌표계 동작 도중 작업 가능 영역을 넘어섭니다.\n- 특이점/데드존과 너무 가까운 자세일 수 있습니다.\n- 이를 피하도록 동작을 재생성하세요.)", R"(EMS Status : Arm-strech condition\n- Cartesian motion reached out a limit of reachable workspace.\n- It may be too close to the singularity / dead zone.\n- Require to re-generate the motion to avoid this condition.)"} },
{ 109, {R"(EMS 상태 : 관절 제한 범위 벗어남\n- 관절 각도가 제한 범위를 벗어납니다.)", R"(EMS Status: Joint angle limit over\n- Joint angle is over its limits)"} },
{ 110, {R"(EMS 상태 : N/A)", R"(EMS Status : N/A)"} },
{ 111, {R"(EMS 상태 : N/A)", R"(EMS Status : N/A)"} },
{ 112, {R"(EMS 상태 : N/A)", R"(EMS Status : N/A)"} },
{ 113, {R"(EMS 상태 : N/A)", R"(EMS Status : N/A)"} },
{ 114, {R"(EMS 상태 : N/A)", R"(EMS Status : N/A)"} },
{ 115, {R"(Rainbow FT :HWSFT 센서가 연결되어 있지 않습니다.)", R"(Rainbow FT : HWSFT sensor is not connected)"} },
{ 116, {R"(Rainbow FT :HWSFT 센서 초기화 (Nulling)을 수행하였습니다.)", R"(Rainbow FT :HWSFT sensor nulling is done)"} },
{ 117, {R"(Rainbow FT : 외부 F/T센서로 HWSFT가 선택되었습니다.\n전체 시스템을 재부팅하세요.)", R"(Rainbow FT : HWSFT is selected for the external F/T sensor.\nRe-boot all systems)"} },
{ 118, {R"(Rainbow FT : 정의되지 않음)", R"(Rainbow FT : N/A)"} },
{ 119, {R"(Rainbow FT : 정의되지 않음)", R"(Rainbow FT : N/A)"} },
{ 120, {R"(Rainbow FT : 정의되지 않음)", R"(Rainbow FT : N/A)"} },
{ 121, {R"(모션 레코딩 : 녹화가 종료되었습니다.\n저장을 원할 시 아래 버튼을 누르세요.)", R"(Motion Record : Recorindg done.\nPress Save button if you want to save this record.)"} },
{ 122, {R"(모션 레코딩 : 파일 저장이 완료되었습니다.)", R"(Motion Record : File save done :))"} },
{ 123, {R"(모션 레코딩 : 파일 이름을 입력해야 합니다.)", R"(Motion Record : Please enter file name)"} },
{ 124, {R"(모션 레코딩 : 녹화 최대 시간 (100초)를 넘어섭니다.)", R"(Motion Record : Maximum Record time (100 sec) over.)"} },
{ 125, {R"(모션 레코딩 : 녹화를 시작합니다.)", R"(Motion Record : Start Recording)"} },
{ 126, {R"(모션 레코딩 : 정의되지 않음)", R"(Motion Record : N/A)"} },
{ 127, {R"(모션 레코딩 : 정의되지 않음)", R"(Motion Record : N/A)"} },
{ 128, {R"(로봇 TCP가 해당 위치에 도착했습니다.)", R"(Robot TCP has arrived at that location.)"} },
{ 129, {R"(로봇 관절각도가 해당 위치에 도착했습니다.)", R"(Robot Joint angles have arrived at that location.)"} },
{ 130, {R"(문자열 길이가 너무 깁니다 !!)", R"(Too Long String !!)"} },
{ 131, {R"(모니터링 문자열 길이가 너무 깁니다 !!)", R"(Too Long Monitoring String !!)"} },
{ 132, {R"(사용 가능한 시리얼 통신 장비가 없습니다 !!)", R"(No Serial Communication Device !!)"} },
{ 133, {R"(Begin (시작 위치) 각도 획득에 실패하였습니다 !! [NO FILE])", R"(Fail to get Begin Angles !! [NO FILE])"} },
{ 134, {R"(Begin (시작 위치) 각도 획득에 실패하였습니다 !! [WRONG TSIZE])", R"(Fail to get Begin Angles !! [WRONG SIZE])"} },
{ 135, {R"(Begin (시작 위치) 각도 획득에 실패하였습니다 !! [WRONG FORMAT])", R"(Fail to get Begin Angles !! [WRONG FORMAT])"} },
{ 136, {R"(Begin (시작 위치) 각도 획득에 실패하였습니다 !! [CRASHED])", R"(Fail to get Begin Angles !! [CRASHED])"} },
{ 137, {R"(Begin (시작 위치) 각도 획득에 실패하였습니다 !! [N/A])", R"(Fail to get Begin Angles !! [N/A])"} },
{ 138, {R"(Begin (시작 위치) 각도 획득에 실패하였습니다 !! [N/A])", R"(Fail to get Begin Angles !! [N/A])"} },
{ 139, {R"(선택된 관절의 0점을 새롭게 설정하였습니다.\n이를 시스템에 반영하려면 로봇팔을 반드시 껐다 켜야 합니다.)", R"(Fine Zero Point for selected joint is RESET !!!! \nTurn Off and On again the power to adjust new angle)"} },
{ 140, {R"(관절 0점 재설정이 가능한 조건이 아닙니다.)", R"(Fine Zero Fail : Condition is not permitted)"} },
{ 141, {R"(함수의 입력 인자 개수가 잘못되었습니다.)", R"(Number of function parameter is wrong)"} },
{ 142, {R"(힘제어: 목표 값이 가능한 범주를 넘어갑니다.)", R"(Force Control: Tracking value bound over)"} },
{ 143, {R"(힘제어: 목표 속도 값이 가능한 범주를 넘어갑니다.)", R"(Force Control: Speed limit bound over)"} },
{ 144, {R"(힘제어: 선택한 센서가 연결되지 않았습니다.)", R"(Force Control: Sensor is not detected)"} },
{ 145, {R"(힘제어: 지원하지 않는 장비가 선택되었습니다.)", R"(Force Control: Wrong sensor selection)"} },
{ 146, {R"(힘제어: 프레임 선택이 잘못되었습니다.)", R"(Force Control: Wrong frame selection)"} },
{ 147, {R"(힘제어: 특이점 영역에서는 힘제어가 불가능 합니다.)", R"(Force Control: Cannot run this mode in Singular point)"} },
{ 148, {R"(힘제어: 정의되지 않음)", R"(Force Control: N/A)"} },
{ 149, {R"(힘제어: 정의되지 않음)", R"(Force Control: N/A)"} },
{ 150, {R"(아날로그 용접기와 디지털 용접기가 모두 설정되어 있는 상태에서는 이 명령어 사용이 불가능 합니다.)", R"(This command cannot be used when both analog and digital welding machines are set.)"} },
{ 151, {R"(직접교시: 이 기능을 수행할 수 있는 환경 및 조건이 아닙니다.)", R"(Direct Teaching: Cannot run this function)"} },
{ 152, {R"(아크: 아크 발생 입력 신호 대시 시간 초과)", R"(Arc: Time-out about the input signal checking)"} },
{ 153, {R"(아크: 입력 값이 Setup-Device의 설정 범주를 넘어 갑니다.)", R"(Arc: Input value exceeds the setting boundary defined in Setup/Device.)"} },
{ 154, {R"(아크: Setup에서 아날로그 용접기 설정이되어 있지 않습니다.)", R"(Arc: Analog welding machine setting is not set in Setup/Device.)"} },
{ 155, {R"(아크: 시간 설정이 잘못되었습니다.)", R"(Arc: Wrong Time parameter)"} },
{ 156, {R"(아크: 제어박스 전압 생성기 (DAC)에서 초기화 실패 코드가 나타납니다.)", R"(Arc: Initialization failure code appears in the control box voltage generator (DAC).)"} },
{ 157, {R"(와이어 전진 포트와 후진 포트 번호에 같은 값을 넣을 수 없습니다.)", R"(You cannot put the same value for wire forward port and reverse port number.)"} },
{ 158, {R"(선택된 와이어 조작 명령에 대한 신호 포트가 설정되어있지 않습니다.)", R"(The signal port for the selected wire control command is not set.)"} },
{ 159, {R"(Robotus FT : 외부 F/T센서로 RFT806A 가 선택되었습니다.\n전체 시스템을 재부팅하세요.)", R"(Robotus FT : RFT806A is selected for the external F/T sensor.\nRe-boot all systems)"} },
{ 160, {R"(선택된 F/T 센서 연결 여부를 확인하세요.)", R"(Check whether the selected F/T sensor is connected)"} },
{ 161, {R"(AutoTcp: 계산이 완료되었습니다. 설정된 값을 재확인 하세요.)", R"(AutoTcp: Calculation Done. Check the calculated values !)"} },
{ 162, {R"(AutoTCP: 계산에 실패하였습니다. 다음과 같은 가능성을 확인하세요.\n4가지 설정 자세 중 같은 자세가 있으면 안됩니다.\n4가지 설정 자세 중 특이점/데드존 근처 자세가 있으면 안됩니다.)", R"(AutoTcp: Fail to calculate TCP! Check follows:\nYou shouldn't have the same posture out of the 4 setup postures.\nOf the four setting postures, there should be no postures near the singularity/dead zone.)"} },
{ 163, {R"(TCP 정보 변경 실패 : TCP 정보 변경이 동시에 일어납니다.\n프로그램 구조를 확인하세요.)", R"(TCP info change fail : TCP information changes are called at the same time.\nCheck the program architecture.)"} },
{ 164, {R"(TCP 정보 변경 실패 : 동작 중에 TCP 정보 변경이 일어납니다.\n프로그램 구조를 확인하세요.)", R"(TCP info change fail : TCP information changes are called during the motion.\nCheck the program architecture.)"} },
{ 165, {R"(TCP 정보 변경 실패 : 툴 리스트에 존재하지 않는 번호 입력입니다.)", R"(TCP info change fail : No matching data in Tool-List)"} },
{ 166, {R"(TCP 정보 변경 실패 : 페이로드 (질량) 설정이 지원 범주를 넘어갑니다.)", R"(TCP info change fail : Over payload (mass) input)"} },
{ 167, {R"(TCP 정보 변경 실패 : 입력 값이 지원 범주를 넘어 갑니다.)", R"(TCP info change fail : Input parameter(s) is over its bound)"} },
{ 168, {R"(비트조합 : 포트 번호가 사용 가능 범주를 벗어납니다.)", R"(Bit Combination : Un-available port number is entered)"} },
{ 169, {R"(비트조합 : 마지막 포트 번호가 시작 포트 보다 작으면 안됩니다.)", R"(Bit Combination : End-port number must not be less than the Start-port number.)"} },
{ 170, {R"(비트조합 : 입력된 값은 양수 값이 들어가야 합니다.)", R"(Bit Combination : Target value should be positive number (or zero).)"} },
{ 171, {R"(비트조합 : 포트 조합으로 가능한 범주 이상의 값이 입력되었습니다.)", R"(Bit Combination : A value exceeded the possible range for the port combination.)"} },
{ 172, {R"(비트조합 : 포트 범위 중 하나 이상의 포트가 특수 기능으로 이미 설정되어 있습니다.)", R"(Bit Combination : One or more ports in the port range are already set as special function(s))"} },
{ 173, {R"(신호토글 : 잘못된 명령어 입력입니다.)", R"(Signal Toggle : Wrong command input)"} },
{ 174, {R"(신호토글 : 선택된 포트에 특수 기능이 설정되어 있습니다.)", R"(Signal Toggle : One or more ports you selected are already set as special function(s))"} },
{ 175, {R"(단위펄스 : 포트 번호가 사용 가능 범주를 벗어납니다.)", R"(Unit Pulse : Un-available port number is entered)"} },
{ 176, {R"(단위펄스 : 선택된 포트에 특수 기능이 설정되어 있습니다.)", R"(Unit Pulse : One or more ports you selected are already set as special function(s))"} },
{ 177, {R"(단위펄스 : 잘못된 명령어 입력입니다.)", R"(Unit Pulse : Wrong command input)"} },
{ 178, {R"(단위펄스 : 시간 파라미터는 0~2 초 사이 값만 가능합니다.)", R"(Unit Pulse : Time parameter should be in 0~2 second range)"} },
{ 179, {R"(이름/문자열의 길이가 지원 범주를 넘어섭니다. 또는 너무 짧습니다.)", R"(Name/String length exceeds the supported range. Or too short.)"} },
{ 180, {R"(이름/문자열에 사용 불가능한 특수 문자 / 공백이 포함되어 있습니다.)", R"(Name/String contains special characters/spaces that are not allowed.)"} },
{ 181, {R"(해당 설정은 프로그램/로봇 운용 중에 바꾸지 못합니다.)", R"(This setting cannot be changed during program/robot operation.)"} },
{ 182, {R"(통신에러 : 로봇 내부 통신 에러 또는 모터 제어기 에러가 의심됩니다.\n시스템을 전체 재부팅하세요.)", R"(Communication Err : Robot internal communication or Motor controller can be damaged)"} },
{ 183, {R"(통신에러 : 확장 I/O 보드 연결을 확인하세요.)", R"(Communication Err : Check the I/O-Extention Board Connection)"} },
{ 184, {R"(제어박스 프로젝트 정보 획득에 실패하였습니다.)", R"(Fail to get Loaded project file information)"} },
{ 185, {R"(프로그램 재생을 중단하였습니다.\n- 현재 '제어 박스'에 로딩된 프로그램 길이가 너무 짧습니다.\n- 원하는 프로그램이 정확히 '제어 박스'에도 로드 되었는지 확인하세요.)", R"(Program playback has been stopped.\n- The length of the program currently loaded in the'Control box' is too short.\n- Check if the desired program is correctly loaded in the'Control box'.)"} },
{ 186, {R"(리얼/시뮬레이션 모드 전환 실패!\n- 운용 모드 전환에 실패하였습니다. 시스템의 운용상태를 점검하세요.\n- '리얼 모드'는 로봇 팔이 활성화되었을 때만 사용 가능합니다.)", R"(Real/Simulation Mode conversion Fail !\n- Fail to convert operation mode. Check the system operating status.\n- 'Real Mode' is only available when the robot arm is activated.)"} },
{ 187, {R"(디지털 입력을 통해서 프로그램 로드에 실패하였습니다.\n로드가 불가능한 상태 (동작 중, 프로그램 실행 중, 등)입니다.)", R"(Failed to load the program through digital input.\nThe load is not possible now (robot is operating, executing program, etc.).)"} },
{ 188, {R"(디지털 입력을 통해서 프로그램이 제어박스에 로드되었습니다.\n태블릿 Ui에 로드된 프로그램과 일치하지 않을 수 있습니다.)", R"(The program is loaded into the Control box via digital input.\nIt may not match the program loaded on the tablet Ui.)"} },
{ 189, {R"(동작 시간 구속 조건 도달 실패 !\n설정된 시간 안에 해당 동작 수행이 불가능 합니다.\n시간을 늘려주거나 속도 또는 가속도를 높여야 합니다.)", R"(Failure to reach the motion time constraint!\nDesired motion cannot be performed within the set time duration.\nYou need to increase the time or increase velocity / acceleration.)"} },
{ 190, {R"(베타 버전 기능입니다. 이 기능은 현재 사용 불가능합니다.)", R"(This is a beta version feature. This feature is currently not available.)"} },
{ 191, {R"(선택된 관절의 MU 오프셋이 재-조정 되었습니다. 활성화를 진행하려면, 시스템 전체를 재부팅해야 합니다.)", R"(MU-offset value of the selected joint is re-set !!!. Whole system reboot is required for the robot arm activation.)"} },
{ 192, {R"(터치센싱: 설정된 탐색 속도가 너무 빠릅니다.)", R"(Touch Sensing: Configured searching-speed is too fast.)"} },
{ 193, {R"(터치센싱: 설정된 탐색 가속도가 너무 낮습니다.)", R"(Touch Sensing: Configured searching-acceleration is too low.)"} },
{ 194, {R"(터치센싱: 설정된 탐색 거리가 너무 짧거나 깁니다.)", R"(Touch Sensing: Configured searching-distance is too short or long.)"} },
{ 195, {R"(터치센싱: 일부 설정 지점이 너무 가깝습니다.)", R"(Touch Sensing: Some of configuration points are too close.)"} },
{ 196, {R"(터치센싱: 수직 점 설정을 확인하세요.)", R"(Touch Sensing: Check the outer/perpendicular point setting)"} },
{ 197, {R"(터치센싱: 다른 동작 명령이 수행 중 입니다.)", R"(Touch Sensing: Other motion or program is executing.)"} },
{ 198, {R"(터치센싱: 탐색은 시작은, 설정된 탐색 시작 지점에서 시작해야 합니다.)", R"(Touch Sensing: Searching should be start at the searching-start-position.)"} },
{ 199, {R"(터치센싱: 센서 감지가 되었습니다. 가져오기를 통해서 현재 지점 정보를 획득하세요.)", R"(Touch Sensing: Sensor signal is detected. 'Get' the current posture information.)"} },
{ 200, {R"(터치센싱: 탐색 중 센서가 감지되지 않았습니다.)", R"(Touch Sensing: Sensor signal is not detected during the searching process.)"} },
{ 201, {R"(터치센싱: 이 기능을 사용하려면, 설정이 우선되어야 합니다.)", R"(Touch Sensing: To use this function, the 'Touch-sensing configuration' has to be prioritized.)"} },
{ 202, {R"(터치센싱: 이 기능을 사용하려면, 설정 후 탐색이 우선되어야 합니다.)", R"(Touch Sensing: To use this function, the 'Touch-sensing configuration & Search' have to be prioritized.)"} },
{ 203, {R"(터치센싱: 지정된 범위 보다 크게 대상물 움직임이 감지됩니다.)", R"(Touch Sensing: Object movement is detected larger than the specified range.)"} },
{ 204, {R"(직접교시모드: 해당 기능은 Real-Robot 모드에서만 사용가능합니다.)", R"(Direct-Teaching Mode: This function is only available at Real-Robot mode)"} },
{ 205, {R"(직접교시모드: 이 기능은 프로그램 실행 구간을 위한 기능입니다. 현 상태에서 사용 불가능합니다.)", R"(Direct-Teaching Mode: This function is for the program execution section. It is not available in the current state.)"} },
{ 206, {R"(직접교시모드: 현재 직접 교시를 할 수 없는 상태 입니다. (로봇 팔 비활성화 상태 또는 다른 명령어 수행 중))", R"(Direct-Teaching Mode: Currently, Direct teaching mode is not available. (Robot arm is not activated or executing another command))"} },
{ 207, {R"(직접교시모드: 직접 교시 모드를 끝내기 전에 이 기능을 수행할 수 없습니다.)", R"(Direct-Teaching Mode: This function (resume or halt) cannot be performed before exiting the Direct-Teaching mode.)"} },
{ 208, {R"(쓰레드 (병렬 프로그램) 구간에서는 사용할 수 없는 기능이 호출됩니다.)", R"(Functions that cannot be used in the Thread (Parallel-Program) section are called.)"} },
{ 209, {R"(G코드: 선택된 사용자 좌표계 번호가 지원 범위를 넘어섭니다.)", R"(G code: Selected user coordinate system number is out of range.)"} },
{ 210, {R"(G코드: 입력된 속도 값이 최대치를 넘어섭니다.)", R"(G code: Entered speed value exceeds the maximum.)"} },
{ 211, {R"(G코드: 선택된 시작 평면 선택 옵션이 지원 범위를 넘어섭니다.)", R"(G code: Selected initial plane type is out of range.)"} },
{ 212, {R"(G코드: 선택된 파일 형식은 지원하지 않습니다.)", R"(G code: Selected file-format is not supporting.)"} },
{ 213, {R"(G코드: 실행 불가능한 상태에서 이 함수가 호출됩니다.)", R"(G code: Cannot run this function in non-program execution state.)"} },
{ 214, {R"(G코드: 다른 동작이 이미 수행 중 입니다.)", R"(G code: Other motion or command is executing.)"} },
{ 215, {R"(G코드: 입력된 코드 파일이 존재하지 않습니다.)", R"(G code: Entered code file does not exist.)"} },
{ 216, {R"(G코드: 라인(블럭) 개수가 0보다 같거나 작습니다.)", R"(G code: Number of lines (blocks) is less than or equal to zero.)"} },
{ 217, {R"(G코드: 입력된 오프셋 값이 지원 범주를 벗어납니다.)", R"(G code: Entered offset values are out of ranges.)"} },
{ 218, {R"(G코드: 지원하지 않는 G코드 형식이 포함되어 있습니다.)", R"(G code: It contains a G code format that is not supported.)"} },
{ 219, {R"(G코드: 지원하지 않는 명령어 파트 (Chunk)가 존재합니다.)", R"(G code: There is an instruction part (Chunk) that is not supported.)"} },
{ 220, {R"(G코드: 동작 수행에 문제가 발생합니다. 지원되지 않는 문법이 포함되어 있을 수 있습니다.)", R"(G code: There is a problem performing the robot motion. It may contain unsupported grammar.)"} },
{ 221, {R"(G코드: 더미)", R"(G code: Dummy)"} },
{ 222, {R"(Safety 파라미터: 저장이 완료되었습니다.\n가져오기를 한 번 더 해서 이중 체크를 하세요!)", R"(Safety Parameter: Save Done...!!!\nPlease double check these parameters!!)"} },
{ 223, {R"(Safety 파라미터: 저장에 실패하였습니다.\nSafety Board와 이중 체크에 실패하였습니다.)", R"(Safety Parameter: Save Fail ...!!\nCross-checking process with SF board is fail ...!!!)"} },
{ 224, {R"(Safety 파라미터: 저장에 실패하였습니다.\n입력한 파라미터가 설정 가능한 범주를 넘거나, 부호가 올바르지 않습니다.)", R"(Safety Parameter: Save Fail ...!!\nSome input parameter is over its bound.)"} },
{ 225, {R"(Safety 파라미터: 저장된 데이터를 불러왔습니다.)", R"(Safety Parameter: Saved parameters are updated in UI.)"} },
{ 226, {R"(디지털용접: 용접기가 선택되지 않았습니다.<br>Setup에서 용접기를 선택하세요.)", R"(Digital Welding: Welding Machine is not selected.<br>Select the welder in Setup menu.)"} },
{ 227, {R"(디지털용접: Setup에 선택된 용접기 정보와 명령어로 선택된 용접기가 일치하지 않습니다.)", R"(Digital Welding: Welder information in Setup and Command is not matching...!!!)"} },
{ 228, {R"(디지털용접: 용접기와 로봇 제어박스가 동기화되지 않았습니다.)", R"(Digital Welding: Sync between welder and robot control box is not done.)"} },
{ 229, {R"(디지털용접: 용접 아크 발생 대기 시간이 초과되었습니다.)", R"(Digital Welding: Arc generation signal time-out !!!)"} },
{ 230, {R"(디지털용접: 용접기의 파워 준비 신호가 들어오지 않았습니다.)", R"(Digital Welding: Power ready signal was not come.)"} },
{ 231, {R"(디지털용접: 용접기의 상태 준비 신호가 들어오지 않았습니다.)", R"(Digital Welding: Machine ready signal was not come.)"} },
{ 232, {R"(디지털용접: 용접기에서 에러 신호가 발생되고 있습니다.)", R"(Digital Welding: Error signal is coming from the welder.)"} },
{ 233, {R"(디지털 용접: 용접기 터치 센싱 모드가 확인되지 않습니다.)", R"(Digital Welding: Cannot check the welder's touch sensing mode.)"} },
{ 234, {R"(로봇 팔 또는 프로그램이 현재 동작 중 이기 때문에, 본 기능은 사용 불가능 합니다.)", R"(Other motion or program command is still executing...!! Cannot run this function.)"} },
{ 235, {R"(노 아크 옵션은 프로그램 흐름 중 또는 동작 중에는 변경 불가능합니다.<br>정지 또는 일시정지 상태에서 변경 가능합니다.)", R"(No-arc option cannot be changed during program flow or during robot operation.<br>It can be changed in stop or pause state.)"} },
{ 236, {R"(Safety Wall: 설정 Wall 번호가 범위를 벗어납니다.)", R"(Safety Wall: Wall number is over its bound.)"} },
{ 237, {R"(Safety Wall: 설정 옵션 번호가 범위를 벗어납니다.)", R"(Safety Wall: Option parameter is over its bound.)"} },
{ 238, {R"(Safety Wall: 설정 수직 벡터 사이즈가 너무 작습니다. 벽 생성이 불가능합니다.)", R"(Safety Wall: Set Normal vector size is too small.... cannot make plane.)"} },
{ 239, {R"(Safety Wall: 설정 점들이 너무 가까이 있습니다. 벽 생성이 불가능합니다.)", R"(Safety Wall: Set Points are too close... cannot make plane.)"} },
{ 240, {R"(Safety Wall: 설정이 완료되었습니다.)", R"(Safety Wall: Configuration is done!)"} },
{ 241, {R"(부가축: 선택한 모터의 정보가 설정되어있지 않습니다.)", R"(Extended Axis: Configuration information of the selected motor is not set.)"} },
{ 242, {R"(부가축: 선택한 모터의 데이터가 수신되고 있지 않습니다.)", R"(Extended Axis: Data of the selected motor is not receiving.)"} },
{ 243, {R"(부가축: 아직 동작 중인 모터에 새로운 동작 명령이 입력됩니다.)", R"(Extended Axis: A new motion command is input to the motor that is still running.)"} },
{ 244, {R"(부가축: 속도나 가속도 값이 너무 작습니다.)", R"(Extended Axis: Velocity or acceleration value is too small.)"} },
{ 245, {R"(부가축: 속도나 가속도 값이 최대치를 넘어섭니다.)", R"(Extended Axis: Velocity or acceleration value exceeds the maximum.)"} },
{ 246, {R"(부가축: 목표 위치 값이 최대 범위를 벗어납니다.)", R"(Extended Axis: Target position value exceeds the maximum.)"} },
{ 247, {R"(부가축: 설정 정보가 저장되었습니다.)", R"(Extended Axis: Configuratioin is saved.)"} },
{ 248, {R"(뮤직 인터페이스: 호출하는 미디어 파일이 시스템에 존재하지 않습니다.)", R"(Music Interface: Input media-file is not loaded in the system.)"} },
{ 249, {R"(뮤직 인터페이스: 설정한 파일 형식은 지원하지 않습니다.)", R"(Music Interface: Wrong file format is selected.)"} },
{ 250, {R"(뮤직 인터페이스: 설정한 옵션 정보가 잘못되었습니다.)", R"(Music Interface: Wrong setting parameters.)"} },
{ 251, {R"(뮤직 인터페이스: 볼륨 설정에 설정 불가능한 파라미터가 들어가 있습니다.)", R"(Music Interface: Wrong volume setting parameter.)"} },
{ 252, {R"(오늘은 공휴일 입니다. 행복한 하루 보내세요.)", R"(Today is a public holiday. Have a nice day.)"} },
{ 253, {R"(Safety 스위치들의 개패 여부를 확인하세요.)", R"(Check whether the Safety switches are open or closed.)"} },
{ 254, {R"(Safety EMS 1 스위치의 개패 여부를 확인하세요.)", R"(Check whether the Safety EMS 1 switch is open or closed.)"} },
{ 255, {R"(Safety EMS 2 스위치의 개패 여부를 확인하세요.)", R"(Check whether the Safety EMS 2 switch is open or closed.)"} },
{ 256, {R"(Safety PRS 스위치의 개패 여부를 확인하세요.)", R"(Check whether the Safety PRS switch is open or closed.)"} },
{ 257, {R"(Safety HSS 스위치의 개패 여부를 확인하세요.)", R"(Check whether the Safety HSS switch is open or closed.)"} },
{ 258, {R"(Safety SSS 스위치의 개패 여부를 확인하세요.)", R"(Check whether the Safety SSS switch is open or closed.)"} },
{ 259, {R"(이미 비상 직접 교시 모드 기능을 사용 중에 있습니다.)", R"(Already using the emergency direct teach mode function.)"} },
{ 260, {R"(로봇 팔 활성화 과정이 다른 프로세스에 의하여 수행 중 입니다.)", R"(Robot arm activation process is being carried out by another process.)"} },
{ 261, {R"(관절 각도 초기화 과정이 수행된 이력이 있습니다. 전체 시스템 재부팅이 요구됩니다.)", R"(There is a history of the joint angle initialization process. A full system reboot is required.)"} },
{ 262, {R"(관절 통신 체크 과정 중 미확인 ID가 감지됩니다. Type 6)", R"(Unidentified ID is detected during joint communication check process. Type 6)"} },
{ 263, {R"(관절 통신 체크 과정 중 미확인 ID가 감지됩니다. Type 7)", R"(Unidentified ID is detected during joint communication check process. Type 7)"} },
{ 264, {R"(관절 통신 체크 과정 중 관절 0번이 정상적으로 인식되고 있지 않습니다.)", R"(During joint communication check process, joint 0 is not recognized normally.)"} },
{ 265, {R"(관절 통신 체크 과정 중 관절 1번이 정상적으로 인식되고 있지 않습니다.)", R"(During joint communication check process, joint 1 is not recognized normally.)"} },
{ 266, {R"(관절 통신 체크 과정 중 관절 2번이 정상적으로 인식되고 있지 않습니다.)", R"(During joint communication check process, joint 2 is not recognized normally.)"} },
{ 267, {R"(관절 통신 체크 과정 중 관절 3번이 정상적으로 인식되고 있지 않습니다.)", R"(During joint communication check process, joint 3 is not recognized normally.)"} },
{ 268, {R"(관절 통신 체크 과정 중 관절 4번이 정상적으로 인식되고 있지 않습니다.)", R"(During joint communication check process, joint 4 is not recognized normally.)"} },
{ 269, {R"(관절 통신 체크 과정 중 관절 5번이 정상적으로 인식되고 있지 않습니다.)", R"(During joint communication check process, joint 5 is not recognized normally.)"} },
{ 270, {R"(관절 통신 체크 과정 실패.)", R"(Joint communication check process failed.)"} },
{ 271, {R"(툴 플랜지 통신 체크 과정 실패.)", R"(Tool flange communication check process failed.)"} },
{ 272, {R"(관절 0번이 사용자의 각도 확인 및 초기화를 요구합니다. [PVL])", R"(Joint No. 0 requests the user's angle confirmation and initialization. [PVL])"} },
{ 273, {R"(관절 1번이 사용자의 각도 확인 및 초기화를 요구합니다. [PVL])", R"(Joint No. 1 requests the user's angle confirmation and initialization. [PVL])"} },
{ 274, {R"(관절 2번이 사용자의 각도 확인 및 초기화를 요구합니다. [PVL])", R"(Joint No. 2 requests the user's angle confirmation and initialization. [PVL])"} },
{ 275, {R"(관절 3번이 사용자의 각도 확인 및 초기화를 요구합니다. [PVL])", R"(Joint No. 3 requests the user's angle confirmation and initialization. [PVL])"} },
{ 276, {R"(관절 4번이 사용자의 각도 확인 및 초기화를 요구합니다. [PVL])", R"(Joint No. 4 requests the user's angle confirmation and initialization. [PVL])"} },
{ 277, {R"(관절 5번이 사용자의 각도 확인 및 초기화를 요구합니다. [PVL])", R"(Joint No. 5 requests the user's angle confirmation and initialization. [PVL])"} },
{ 278, {R"(관절 엔코더가 사용자의 각도 확인 및 초기화를 요구합니다. [PVL])", R"(Joint encoder requests the user's angle confirmation and initialization. [PVL])"} },
{ 279, {R"(관절 엔코더에서 불안정한 신호가 수신됩니다. [NONI])", R"(An unstable signal is received from the joint encoder. [NONI])"} },
{ 280, {R"(관절 0번의 각도가 최대 + 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 - 방향으로 돌려야 합니다.)", R"(The angle of joint 0 is out of the maximum + range. You must manually release the brake to turn the joint in the - direction.)"} },
{ 281, {R"(관절 1번의 각도가 최대 + 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 - 방향으로 돌려야 합니다.)", R"(The angle of joint 1 is out of the maximum + range. You must manually release the brake to turn the joint in the - direction.)"} },
{ 282, {R"(관절 2번의 각도가 최대 + 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 - 방향으로 돌려야 합니다.)", R"(The angle of joint 2 is out of the maximum + range. You must manually release the brake to turn the joint in the - direction.)"} },
{ 283, {R"(관절 3번의 각도가 최대 + 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 - 방향으로 돌려야 합니다.)", R"(The angle of joint 3 is out of the maximum + range. You must manually release the brake to turn the joint in the - direction.)"} },
{ 284, {R"(관절 4번의 각도가 최대 + 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 - 방향으로 돌려야 합니다.)", R"(The angle of joint 4 is out of the maximum + range. You must manually release the brake to turn the joint in the - direction.)"} },
{ 285, {R"(관절 5번의 각도가 최대 + 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 - 방향으로 돌려야 합니다.)", R"(The angle of joint 5 is out of the maximum + range. You must manually release the brake to turn the joint in the - direction.)"} },
{ 286, {R"(관절 0번의 각도가 최대 - 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 + 방향으로 돌려야 합니다.)", R"(The angle of joint 0 is out of the maximum - range. You must manually release the brake to turn the joint in the + direction.)"} },
{ 287, {R"(관절 1번의 각도가 최대 - 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 + 방향으로 돌려야 합니다.)", R"(The angle of joint 1 is out of the maximum - range. You must manually release the brake to turn the joint in the + direction.)"} },
{ 288, {R"(관절 2번의 각도가 최대 - 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 + 방향으로 돌려야 합니다.)", R"(The angle of joint 2 is out of the maximum - range. You must manually release the brake to turn the joint in the + direction.)"} },
{ 289, {R"(관절 3번의 각도가 최대 - 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 + 방향으로 돌려야 합니다.)", R"(The angle of joint 3 is out of the maximum - range. You must manually release the brake to turn the joint in the + direction.)"} },
{ 290, {R"(관절 4번의 각도가 최대 - 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 + 방향으로 돌려야 합니다.)", R"(The angle of joint 4 is out of the maximum - range. You must manually release the brake to turn the joint in the + direction.)"} },
{ 291, {R"(관절 5번의 각도가 최대 - 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 + 방향으로 돌려야 합니다.)", R"(The angle of joint 5 is out of the maximum - range. You must manually release the brake to turn the joint in the + direction.)"} },
{ 292, {R"(관절 각도가 사용 최대 범주를 벗어납니다. 수동으로 브레이크를 해제하여 관절을 범주 안으로 돌려야 합니다.)", R"(Joint angle is outside the maximum range of use. You must manually release the brakes to turn the joint into range.)"} },
{ 293, {R"(관절 엔코더 각도 또는 설치 각도 설정 또는 센서에 이상이 있습니다. 각도 동기화 오류)", R"(There is a problem with the joint encoder angle or installation angle setting or sensor. Angle synchronization error)"} },
{ 294, {R"(로봇 팔의 캘리브레이션 보정치 수신 과정에 문제가 있습니다.)", R"(There is a problem in the process of receiving the calibration correction value of the robot arm.)"} },
{ 295, {R"(로봇 팔 준비 과정 중에는 직접교시 버튼을 누르고 있으면 안됩니다.)", R"(Do not press and hold the direct teach button during the robotic arm preparation process.)"} },
{ 296, {R"(관절 모터 제어기의 모드 전환에 실패하였습니다.)", R"(Failed to change the mode of the joint motor controller.)"} },
{ 297, {R"(비상 직접교시 사용이 준비되었습니다. 직접교시 버튼을 누르면 로봇 팔 비상운용이 가능합니다. 사용 후 반드시 전력을 꺼주세요.)", R"(Ready for emergency direct teaching use. Emergency operation of the robot arm is possible by pressing the direct teaching button. Be sure to turn off the power after use.)"} },
{ 298, {R"(AutoTCP: 계산에 실패하였습니다. 다음과 같은 가능성을 확인하세요.\n8가지 설정 자세 중 같은 자세가 있으면 안됩니다.\n8가지 설정 자세 중 특이점/데드존 근처 자세가 있으면 안됩니다.)", R"(AutoTcp: Fail to calculate TCP! Check follows:\nYou shouldn't have the same posture out of the 8 setup postures.\nOf the eight setting postures, there should be no postures near the singularity/dead zone.)"} },
{ 299, {R"(제어박스 SMPS 파워서플라이에 과전류 이력 또는 저전압 이력이 남아있습니다. 제어박스 재부팅이 요구됩니다. 문제가 지속된다면 제조사에 문의하세요.)", R"(The history of overcurrent or undervoltage remains in the control box SMPS power supply. A control box reboot is required. If the problem persists, contact the manufacturer.)"} },
{ 300, {R"(ROS: 수신된 궤적의 사이즈가 0인 상태에서 동작이 호출됩니다.)", R"(ROS: Motion is called when the size of the received trajectory is 0.)"} },
{ 301, {R"(ROS: 수신된 궤적의 사이즈와 동작 명령어에 명시된 사이즈가 일치하지 않습니다.)", R"(ROS: Size of the received trajectory and the size specified in the motion command do not match.)"} },
{ 302, {R"(ROS: 시간 파라미터 값은 항상 양수가 수신되어야 합니다.)", R"(ROS: Time parameter value must always be received as a positive number.)"} },
{ 303, {R"(ROS: 시간 파라미터는 오름차순으로 증가해야 합니다.)", R"(ROS: Time parameter must increase in ascending order.)"} },
{ 304, {R"(ROS: 궤적의 시작 지점은, 로봇의 마지막 위치와 일치해야 합니다.)", R"(ROS: The starting point of the trajectory should coincide with the last position of the robot.)"} },
{ 305, {R"(프로그램 전환: 이미 동일한 작업이 수행 중 입니다.)", R"(Program Convert: Same operation is already being performed.)"} },
{ 306, {R"(프로그램 전환: 잘못된 옵션 번호가 입력되었습니다.)", R"(Program Convert: Incorrect option number has been entered.)"} },
{ 307, {R"(프로그램 전환: 로봇 동작 중에는 이 기능을 호출할 수 없습니다.)", R"(Program Convert: This function cannot be called while the robot is in motion.)"} },
{ 308, {R"(프로그램 전환: 기존 프로그램 종료 확인 과정에서 시간 초과가 발생하였습니다.)", R"(Program Convert: Timeout occurred in the process of confirming the end of the existing program.)"} },
{ 309, {R"(프로그램 전환: 새로운 프로그램을 불러오는 도중 시간 초과가 발생하였습니다.)", R"(Program Convert: Timeout occurred while loading a new program.)"} },
{ 310, {R"(프로그램 전환: 다른 불러오기 기능이 이미 수행 중 입니다.)", R"(Program Convert: Another LOAD function is already being performed.)"} },
{ 311, {R"(프로그램 전환: 호출된 프로그램이 제어박스에 존재하지 않거나 손상되었습니다.)", R"(Program Convert: The called program does not exist or is damaged in the control box.)"} },
{ 312, {R"(프로그램 전환: 호출된 프로그램이 제어박스에 존재하지만 손상되었습니다.)", R"(Program Convert: The called program exists in the control box, but it is damaged.)"} },
{ 313, {R"(CAN전송: ID 또는 DLC 또는 채널이 범위를 벗어납니다.)", R"(CAN transmission: ID or DLC or channel is out of range.)"} },
{ 314, {R"(부가축: 잘못된 부가축 번호를 수신하였습니다.)", R"(External Axis: An incorrect auxiliary axis number has been received.)"} },
{ 315, {R"(부가축: 축 캘리브레이션을 위해서는 최소 4점 이상의 정보가 필요합니다.)", R"(External Axis: At least 4 points of information are required for axis calibration.)"} },
{ 316, {R"(부가축: 선택된 번호의 축은 설정되지 않은 축 입니다. Setup 페이지를 확인하세요.)", R"(External Axis: The axis of the selected number is an unset axis. Check the Setup page.)"} },
{ 317, {R"(부가축: 축 캘리브레이션 과정 중에는 같은 축을 대상으로 정보를 저장해야 합니다.)", R"(External Axis: During the axis calibration process, the information must be saved for the same axis.)"} },
{ 318, {R"(부가축: 축 캘리브리이션 저장 데이터 중, 중복된 데이터/너무 가까운 데이터가 존재합니다.)", R"(External Axis: Among the saved data for axis calibration, there are duplicate data/too close data.)"} },
{ 319, {R"(부가축: 축 캘리브리이션에 정보가 추가되었습니다.)", R"(External Axis: Information has been added to axis calibration.)"} },
{ 320, {R"(부가축: 선택된 축의 캘리브리이션이 완료되었습니다.)", R"(External Axis: Calibration of the selected axis is complete.)"} },
{ 321, {R"(부가축: 선택된 축의 캘리브리이션 과정을 실패하였습니다. 오차가 허용범위 이상입니다.)", R"(External Axis: The calibration process for the selected axis has failed. The error is more than the allowable range.)"} },
{ 322, {R"(부가축: 다른 동작/프로그램 구동중에는 해당 기능 수행이 불가능 합니다.)", R"(External Axis: During other operation/program operation, the corresponding function cannot be performed.)"} },
{ 323, {R"(부가축: 부가축 캘리브레이션을 시작하세요!)", R"(External Axis: Start Calibration ... !!!)"} },
{ 324, {R"(로봇 동작 속도 또는 가속도가 사용 가능 범주 밖 입니다.)", R"(Robot motion speed or acceleration is outside the usable range.)"} },
{ 325, {R"(부가축 속도 또는 가속도가 사용 가능 범주 밖 입니다.)", R"(External axis speed or acceleration is outside the usable range.)"} },
{ 326, {R"(부가축 목표값이 사용 가능 범주 밖 입니다.)", R"(External axis target value is out of the usable range.)"} },
{ 327, {R"(오프셋 또는 시프트 기능의 수학적 연산 불가능 지점 입니다.)", R"(It is the point where the mathematical operation of the offset or shift function is impossible.)"} },
{ 328, {R"(입력 신호를 통하여 불러올 프로그램이 설정되어있지 않습니다.)", R"(The program to be loaded through the input signal is not set.)"} },
{ 329, {R"(제어박스에 저장되어 있지 않은 프로젝트 (.wsl) 이름입니다.)", R"(This is the name of the project (.wsl) that is not saved in the control box.)"} },
{ 330, {R"(설정된 프로젝트에 문법적 오류가 존재합니다.)", R"(A grammatical error exists in the set project.)"} },
{ 331, {R"(호출된 파일 정보가 제어박스에 존재하지 않습니다.)", R"(The called file information does not exist in the Control box.)"} },
{ 332, {R"(호출된 CSV 파일의 행의 형식이 지원되지 않는 형태입니다.)", R"(The format of the row of the called CSV file is not supported.)"} },
{ 333, {R"(호출된 행의 위치가 파일의 길이를 벗어납니다.)", R"(The position of the called row is outside the length of the file.)"} },
{ 334, {R"(호출된 열의 위치가 파일의 길이를 벗어납니다.)", R"(The position of the called column is outside the length of the file.)"} },
{ 335, {R"(참조된 인덱스에서 정보를 획득하는데 실패하였습니다.)", R"(Failed to get information from the referenced index.)"} },
{ 336, {R"(숫자 형태가 아닌 정보가 호출된 위치에 저장되어 있습니다.)", R"(Non-numeric information is stored in the called location.)"} },
{ 337, {R"(기존에 수행 중이던 너트러너 명령어가 끝나지 않았습니다.)", R"(The previously executed nutrunner command did not end.)"} },
{ 338, {R"(너트러너 명령어 종료 확인 시간 초과.)", R"(Nutrunner instruction exit check timeout.)"} },
{ 339, {R"(호출된 쓰레드는 이벤트 쓰레드가 아닙니다.)", R"(The called thread is not the event thread.)"} },
{ 340, {R"(호출된 쓰레드에 내용이 없습니다.)", R"(The called thread has no content.)"} },
{ 341, {R"(아직 명령어 수행이 끝나지 않은 이벤트 쓰레드가 호출됩니다.)", R"(The event thread that has not yet finished executing the command is called.)"} },
{ 342, {R"(해당 기능은 프로그램 재생 중에만 사용 가능합니다.)", R"(This function is only available during program playback.)"} },
{ 343, {R"(TCP/IP Ui 연결 모드에서는 이 기능을 사용할 수 없습니다.)", R"(This feature is not available in TCP/IP UI connection mode.)"} },
{ 344, {R"(관절 보호 에러 : Big Error 0)", R"(Joint Protection Error : Big Error 0)"} },
{ 345, {R"(관절 보호 에러 : Big Error 1)", R"(Joint Protection Error : Big Error 1)"} },
{ 346, {R"(관절 보호 에러 : Big Error 2)", R"(Joint Protection Error : Big Error 2)"} },
{ 347, {R"(관절 보호 에러 : Big Error 3)", R"(Joint Protection Error : Big Error 3)"} },
{ 348, {R"(관절 보호 에러 : Big Error 4)", R"(Joint Protection Error : Big Error 4)"} },
{ 349, {R"(관절 보호 에러 : Big Error 5)", R"(Joint Protection Error : Big Error 5)"} },
{ 350, {R"(관절 보호 에러 : Communication Input Error 0)", R"(Joint Protection Error : Communication Input Error 0)"} },
{ 351, {R"(관절 보호 에러 : Communication Input Error 1)", R"(Joint Protection Error : Communication Input Error 1)"} },
{ 352, {R"(관절 보호 에러 : Communication Input Error 2)", R"(Joint Protection Error : Communication Input Error 2)"} },
{ 353, {R"(관절 보호 에러 : Communication Input Error 3)", R"(Joint Protection Error : Communication Input Error 3)"} },
{ 354, {R"(관절 보호 에러 : Communication Input Error 4)", R"(Joint Protection Error : Communication Input Error 4)"} },
{ 355, {R"(관절 보호 에러 : Communication Input Error 5)", R"(Joint Protection Error : Communication Input Error 5)"} },
{ 356, {R"(관절 보호 에러 : Motor Rotor JAM Error 0)", R"(Joint Protection Error : Motor Rotor JAM Error 0)"} },
{ 357, {R"(관절 보호 에러 : Motor Rotor JAM Error 1)", R"(Joint Protection Error : Motor Rotor JAM Error 1)"} },
{ 358, {R"(관절 보호 에러 : Motor Rotor JAM Error 2)", R"(Joint Protection Error : Motor Rotor JAM Error 2)"} },
{ 359, {R"(관절 보호 에러 : Motor Rotor JAM Error 3)", R"(Joint Protection Error : Motor Rotor JAM Error 3)"} },
{ 360, {R"(관절 보호 에러 : Motor Rotor JAM Error 4)", R"(Joint Protection Error : Motor Rotor JAM Error 4)"} },
{ 361, {R"(관절 보호 에러 : Motor Rotor JAM Error 5)", R"(Joint Protection Error : Motor Rotor JAM Error 5)"} },
{ 362, {R"(관절 보호 에러 : Motor Current Over Error 0)", R"(Joint Protection Error : Motor Current Over Error 0)"} },
{ 363, {R"(관절 보호 에러 : Motor Current Over Error 1)", R"(Joint Protection Error : Motor Current Over Error 1)"} },
{ 364, {R"(관절 보호 에러 : Motor Current Over Error 2)", R"(Joint Protection Error : Motor Current Over Error 2)"} },
{ 365, {R"(관절 보호 에러 : Motor Current Over Error 3)", R"(Joint Protection Error : Motor Current Over Error 3)"} },
{ 366, {R"(관절 보호 에러 : Motor Current Over Error 4)", R"(Joint Protection Error : Motor Current Over Error 4)"} },
{ 367, {R"(관절 보호 에러 : Motor Current Over Error 5)", R"(Joint Protection Error : Motor Current Over Error 5)"} },
{ 368, {R"(관절 보호 에러 : Motor Position Limit Error 0)", R"(Joint Protection Error : Motor Position Limit Error 0)"} },
{ 369, {R"(관절 보호 에러 : Motor Position Limit Error 1)", R"(Joint Protection Error : Motor Position Limit Error 1)"} },
{ 370, {R"(관절 보호 에러 : Motor Position Limit Error 2)", R"(Joint Protection Error : Motor Position Limit Error 2)"} },
{ 371, {R"(관절 보호 에러 : Motor Position Limit Error 3)", R"(Joint Protection Error : Motor Position Limit Error 3)"} },
{ 372, {R"(관절 보호 에러 : Motor Position Limit Error 4)", R"(Joint Protection Error : Motor Position Limit Error 4)"} },
{ 373, {R"(관절 보호 에러 : Motor Position Limit Error 5)", R"(Joint Protection Error : Motor Position Limit Error 5)"} },
{ 374, {R"(관절 보호 에러 : Board Mode Error 0)", R"(Joint Protection Error : Board Mode Error 0)"} },
{ 375, {R"(관절 보호 에러 : Board Mode Error 1)", R"(Joint Protection Error : Board Mode Error 1)"} },
{ 376, {R"(관절 보호 에러 : Board Mode Error 2)", R"(Joint Protection Error : Board Mode Error 2)"} },
{ 377, {R"(관절 보호 에러 : Board Mode Error 3)", R"(Joint Protection Error : Board Mode Error 3)"} },
{ 378, {R"(관절 보호 에러 : Board Mode Error 4)", R"(Joint Protection Error : Board Mode Error 4)"} },
{ 379, {R"(관절 보호 에러 : Board Mode Error 5)", R"(Joint Protection Error : Board Mode Error 5)"} },
{ 380, {R"(관절 보호 에러 : Board Temperature Error 0)", R"(Joint Protection Error : Board Temperature Error 0)"} },
{ 381, {R"(관절 보호 에러 : Board Temperature Error 1)", R"(Joint Protection Error : Board Temperature Error 1)"} },
{ 382, {R"(관절 보호 에러 : Board Temperature Error 2)", R"(Joint Protection Error : Board Temperature Error 2)"} },
{ 383, {R"(관절 보호 에러 : Board Temperature Error 3)", R"(Joint Protection Error : Board Temperature Error 3)"} },
{ 384, {R"(관절 보호 에러 : Board Temperature Error 4)", R"(Joint Protection Error : Board Temperature Error 4)"} },
{ 385, {R"(관절 보호 에러 : Board Temperature Error 5)", R"(Joint Protection Error : Board Temperature Error 5)"} },
{ 386, {R"(관절 보호 에러 : Tracking match Error 0)", R"(Joint Protection Error : Tracking match Error 0)"} },
{ 387, {R"(관절 보호 에러 : Tracking match Error 1)", R"(Joint Protection Error : Tracking match Error 1)"} },
{ 388, {R"(관절 보호 에러 : Tracking match Error 2)", R"(Joint Protection Error : Tracking match Error 2)"} },
{ 389, {R"(관절 보호 에러 : Tracking match Error 3)", R"(Joint Protection Error : Tracking match Error 3)"} },
{ 390, {R"(관절 보호 에러 : Tracking match Error 4)", R"(Joint Protection Error : Tracking match Error 4)"} },
{ 391, {R"(관절 보호 에러 : Tracking match Error 5)", R"(Joint Protection Error : Tracking match Error 5)"} },
{ 392, {R"(이 기능은 용접 중에만 사용가능합니다.)", R"(This function is only available during welding.)"} },
{ 393, {R"(배열 정보에서 참조 가능한 인덱스 범위를 벗어 납니다. )", R"(Referenceable index range in array information is out of range.)"} },
{ 394, {R"(모드버스 클라이언트 : 서버에 연결 실패하였습니다.)", R"(Modbus Client: Failed to connect to the server.)"} },
{ 395, {R"(메일 전송 실패)", R"(Failed to send mail)"} },
{ 396, {R"(로봇 전력 공급 차단: 로봇 베이스가 과도하게 기울었습니다.)", R"(Shut off robot power supply: The robot base is tilted excessively.)"} },
{ 397, {R"(패턴: 프로그램에서 사용 가능한 패턴 개수를 넘어섭니다.)", R"(Pattern: The number of patterns available in the program is exceeded.)"} },
{ 398, {R"(패턴: 패턴 구성시, 각 변에는 최소 2 이상이 입력되어야 합니다.)", R"(Pattern: When configuring a pattern, at least 2 must be entered on each side.)"} },
{ 399, {R"(패턴: 입력된 패턴 ID를 검색하는데 실패하였습니다.)", R"(Pattern: Failed to retrieve the entered pattern ID.)"} },
{ 400, {R"(패턴: 동일한 패턴 ID를 사용하는 패턴들이 존재합니다.)", R"(Pattern: There are patterns using the same pattern ID.)"} },
{ 401, {R"(Robotus FT : 외부 F/T센서로 RFT64SB 가 선택되었습니다.\n전체 시스템을 재부팅하세요.)", R"(Robotus FT : RFT64SB is selected for the external F/T sensor.\nRe-boot all systems)"} },
{ 402, {R"(이 기능은 로봇 팔이 활성화 된 이후에 사용 가능합니다.)", R"(This function is only available after the robot arm is activated.)"} },
{ 403, {R"(OnRobot HEX FT : 외부 F/T센서로 OnRobot HEX 가 선택되었습니다.\n전체 시스템을 재부팅하세요.)", R"(OnRobot HEX FT : OnRobot HEX is selected for the external F/T sensor.\nRe-boot all systems)"} },
{ 404, {R"(Interface에서 사용하고자 하는 소켓 0번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(Socket number 0 to be used in the Interface has already been set with another special function.)"} },
{ 405, {R"(Interface에서 사용하고자 하는 소켓 1번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(Socket number 1 to be used in the Interface has already been set with another special function.)"} },
{ 406, {R"(Interface에서 사용하고자 하는 소켓 2번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(Socket number 2 to be used in the Interface has already been set with another special function.)"} },
{ 407, {R"(Interface에서 사용하고자 하는 소켓 3번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(Socket number 3 to be used in the Interface has already been set with another special function.)"} },
{ 408, {R"(Interface에서 사용하고자 하는 소켓 4번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(Socket number 4 to be used in the Interface has already been set with another special function.)"} },
{ 409, {R"(사용하고자 하는 소켓 번호 0번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(The socket number 0 you want to use is already set with another special function.)"} },
{ 410, {R"(사용하고자 하는 소켓 번호 1번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(The socket number 1 you want to use is already set with another special function.)"} },
{ 411, {R"(사용하고자 하는 소켓 번호 2번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(The socket number 2 you want to use is already set with another special function.)"} },
{ 412, {R"(사용하고자 하는 소켓 번호 3번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(The socket number 3 you want to use is already set with another special function.)"} },
{ 413, {R"(사용하고자 하는 소켓 번호 4번이 이미 다른 특수 기능으로 설정되어 있습니다.)", R"(The socket number 4 you want to use is already set with another special function.)"} },
{ 414, {R"(로봇 팔 활성화 과정 중에는 프로그램을 시작할 수 없습니다.)", R"(The program cannot be started during the robot arm activation process.)"} },
{ 415, {R"(디지털 입력 특수 기능인 Program Start Block 신호가 들어오고 있어서 프로그램을 시작할 수 없습니다.)", R"(The program cannot be started because the digital input special function Program Start Block signal is being received.)"} },
{ 416, {R"(제이벅스 네트워크 설정이 변경되었습니다. 정상 작동을 위해서 반드시 로봇 제어박스를 재부팅하세요.)", R"(The control box network settings have been changed. Be sure to reboot the robot control box for normal operation.)"} },
{ 417, {R"(핸드 컨트롤러의 조그 버튼에 대한 기능 정의가 변경되었습니다.)", R"(The function definition for the jog button on the hand controller has been changed.)"} },
{ 418, {R"(동작과 관련된 설정은 안전을 위하여 누를때와 뗄때의 버튼 기능이 고정됩니다.)", R"(For the settings related to operation, the button functions when pressed and released are fixed for safety.)"} },
{ 419, {R"(인터페이스 통신 기능을 사용하기 위해서는 서버와 연결 및 설정 과정이 선행되어야 합니다.)", R"(In order to use the interface communication function, the process of connecting and setting with the server must be preceded.)"} },
{ 420, {R"(인터페이스에서 소켓 0번을 사용하여 PLC-HMI-Vision 서버에 접속하는데 실패하였습니다.)", R"(Failed to connect to PLC-HMI-Vision server using socket 0 in the Interface.)"} },
{ 421, {R"(인터페이스에서 소켓 1번을 사용하여 PLC-HMI-Vision 서버에 접속하는데 실패하였습니다.)", R"(Failed to connect to PLC-HMI-Vision server using socket 1 in the Interface.)"} },
{ 422, {R"(인터페이스에서 소켓 2번을 사용하여 PLC-HMI-Vision 서버에 접속하는데 실패하였습니다.)", R"(Failed to connect to PLC-HMI-Vision server using socket 2 in the Interface.)"} },
{ 423, {R"(인터페이스에서 소켓 3번을 사용하여 PLC-HMI-Vision 서버에 접속하는데 실패하였습니다.)", R"(Failed to connect to PLC-HMI-Vision server using socket 3 in the Interface.)"} },
{ 424, {R"(인터페이스에서 소켓 4번을 사용하여 PLC-HMI-Vision 서버에 접속하는데 실패하였습니다.)", R"(Failed to connect to PLC-HMI-Vision server using socket 4 in the Interface.)"} },
{ 425, {R"(인터페이스의 소켓 0번을 통한 단일 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write a single variable through socket 0 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 426, {R"(인터페이스의 소켓 1번을 통한 단일 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write a single variable through socket 1 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 427, {R"(인터페이스의 소켓 2번을 통한 단일 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write a single variable through socket 2 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 428, {R"(인터페이스의 소켓 3번을 통한 단일 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write a single variable through socket 3 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 429, {R"(인터페이스의 소켓 4번을 통한 단일 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write a single variable through socket 4 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 430, {R"(인터페이스의 소켓 0번을 통한 단일 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read a single variable through socket 0 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 431, {R"(인터페이스의 소켓 1번을 통한 단일 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read a single variable through socket 1 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 432, {R"(인터페이스의 소켓 2번을 통한 단일 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read a single variable through socket 2 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 433, {R"(인터페이스의 소켓 3번을 통한 단일 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read a single variable through socket 3 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 434, {R"(인터페이스의 소켓 4번을 통한 단일 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read a single variable through socket 4 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 435, {R"(인터페이스의 소켓 0번을 통한 다중 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write array numbers through socket 0 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 436, {R"(인터페이스의 소켓 1번을 통한 다중 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write array numbers through socket 1 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 437, {R"(인터페이스의 소켓 2번을 통한 다중 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write array numbers through socket 2 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 438, {R"(인터페이스의 소켓 3번을 통한 다중 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write array numbers through socket 3 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 439, {R"(인터페이스의 소켓 4번을 통한 다중 변수 쓰기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to write array numbers through socket 4 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 440, {R"(인터페이스의 소켓 0번을 통한 다중 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read array numbers through socket 0 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 441, {R"(인터페이스의 소켓 1번을 통한 다중 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read array numbers through socket 1 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 442, {R"(인터페이스의 소켓 2번을 통한 다중 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read array numbers through socket 2 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 443, {R"(인터페이스의 소켓 3번을 통한 다중 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read array numbers through socket 3 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 444, {R"(인터페이스의 소켓 4번을 통한 다중 변수 읽기에 실패하였습니다. 서버로부터 정상적인 ACK 신호가 도착하지 않았습니다.)", R"(Failed to read array numbers through socket 4 of the Interface. A normal ACK signal did not arrive from the server.)"} },
{ 445, {R"(로봇 팔의 온도가 권장 사용 환경을 벗어납니다. 사용시 유의해세요.)", R"(The temperature of the robot arm is outside the recommended operating environment. Be careful when using.)"} },
{ 446, {R"(위빙 설정 오류 : 축 선택이 올바르지 않습니다. 같은 축은 선택할 수 없습니다.)", R"(Weaving Setting Error: The axis selection is incorrect. The same axis cannot be selected.)"} },
{ 447, {R"(위빙 설정 오류 : 스캐일 값이 허용 범위를 벗어납니다.)", R"(Weaving Setting Error: The scale value is outside the acceptable range.)"} },
{ 448, {R"(위빙 설정 오류 : 오프셋 값은 최대 진폭 크기 이상으로 설정 불가능 합니다.)", R"(Weaving Setting Error: The offset value cannot be set beyond the maximum amplitude.)"} },
{ 449, {R"(Ethernet IP Adaptor On 설정이 저장되었습니다. 설정을 반영하기 위해 시스템 전체 재부팅이 필요합니다.)", R"(Ethernet IP Adapter On settings have been saved. A full system reboot is required for the settings to take effect.)"} },
{ 450, {R"(Ethernet IP Adaptor Off 설정이 저장되었습니다. 설정을 반영하기 위해 시스템 전체 재부팅이 필요합니다.)", R"(Ethernet IP Adapter Off settings have been saved. A full system reboot is required for the settings to take effect.)"} },
{ 451, {R"(Ethernet IP Adaptor 모듈이 설치되었습니다. )", R"(Ethernet IP Adapter module is installed.)"} },
{ 452, {R"(Ethernet IP Adpator 모듈이 제거되었습니다. )", R"(Ethernet IP Adpator module is removed.)"} },
{ 453, {R"(OnRobot Compute Box와 통신 연결에 실패하였습니다.)", R"(Communication connection with OnRobot Compute Box failed.)"} },
{ 454, {R"(OnRobot Compute Box로부터 초기 설정에 대한 ACK를 수신하지 못하였습니다.)", R"(Failed to receive ACK for initial setup from OnRobot Compute Box.)"} },
{ 455, {R"(OnRobot Compute Box로부터 동작 명령에 대한 ACK를 수신하지 못하였습니다.)", R"(Failed to receive ACK for motion command from OnRobot Compute Box.)"} },
{ 456, {R"(OnRobot Compute Box와 연결해 사용하려면 그리퍼 초기 설정을 먼저 수행해야 합니다.)", R"(To connect to the Onrobot Compute Box, user must first perform the gripper initial settings first.)"} },
{ 457, {R"(Side IO Board로부터의 데이터 수신이 끊어졌습니다.\n외부에서 통신 노이즈가 들어오고 있을 수 있습니다.\n제어박스 내부 통신선이 불안정할 수 있습니다.\nIO Board의 Fuse가 끊어졌을 수 있습니다.)", R"(Data reception from the Side IO Board is cut off.\nCommunication noise may be coming from outside.\nThe communication line inside the control box may be unstable.\nThe fuse of the IO Board may be broken.)"} },
{ 458, {R"(DC 48V SMPS의 저전압 출력이 감지됩니다.\nACtoDC48V SMPS 상태를 확인하세요.\n외부 AC 노이즈가 있을 수 있습니다.\n문제가 지속된다면 AC 캐이블을 15분 이상 분리 후 재사용하세요.)", R"(A low voltage output of DC 48V SMPS is detected.\nCheck ACtoDC48V SMPS status.\nThere may be external AC noise.\nIf the problem persists, disconnect the AC cable for at least 15 minutes and reuse it.)"} },
{ 459, {R"(문자열과 같은 명칭의 Point가 존재하지 않습니다.)", R"(Point with the same name as a string does not exist.)"} },
{ 460, {R"(문자열과 같은 명칭의 Joint가 존재하지 않습니다.)", R"(Joint with the same name as a string does not exist.)"} },
{ 461, {R"(제어박스 POWER SWE 오류.\nSMPS 부품이 비정상 작동 중 이거나 제어박스에 접지가 되어있지 않았을 수 있습니다.)", R"(Control box POWER SWE error.\nThe SMPS part may be operating abnormally or the control box may not be grounded.)"} },
{ 462, {R"(통신에러 : 로봇 팔의 관절 0번 통신이 불안정합니다.)", R"(Communication error: The communication of joint 0 of the robot arm is unstable.)"} },
{ 463, {R"(통신에러 : 로봇 팔의 관절 1번 통신이 불안정합니다.)", R"(Communication error: The communication of joint 1 of the robot arm is unstable.)"} },
{ 464, {R"(통신에러 : 로봇 팔의 관절 2번 통신이 불안정합니다.)", R"(Communication error: The communication of joint 2 of the robot arm is unstable.)"} },
{ 465, {R"(통신에러 : 로봇 팔의 관절 3번 통신이 불안정합니다.)", R"(Communication error: The communication of joint 3 of the robot arm is unstable.)"} },
{ 466, {R"(통신에러 : 로봇 팔의 관절 4번 통신이 불안정합니다.)", R"(Communication error: The communication of joint 4 of the robot arm is unstable.)"} },
{ 467, {R"(통신에러 : 로봇 팔의 관절 5번 통신이 불안정합니다.)", R"(Communication error: The communication of joint 5 of the robot arm is unstable.)"} },
{ 468, {R"(통신에러 : 로봇 팔의 툴플랜지 통신이 불안정합니다.)", R"(Communication error: The communication of tool flange of the robot arm is unstable.)"} },
{ 469, {R"(부가축: 0번 관절의 지령 위치와 AC 서보의 엔코더 위치의 차이가 범위를 벗어납니다.)", R"(Extended Axis: The difference between the command position of joint 0 and the encoder position of AC servo is out of range.)"} },
{ 470, {R"(부가축: 1번 관절의 지령 위치와 AC 서보의 엔코더 위치의 차이가 범위를 벗어납니다.)", R"(Extended Axis: The difference between the command position of joint 1 and the encoder position of AC servo is out of range.)"} },
{ 471, {R"(부가축: 2번 관절의 지령 위치와 AC 서보의 엔코더 위치의 차이가 범위를 벗어납니다.)", R"(Extended Axis: The difference between the command position of joint 2 and the encoder position of AC servo is out of range.)"} },
{ 472, {R"(부가축: 3번 관절의 지령 위치와 AC 서보의 엔코더 위치의 차이가 범위를 벗어납니다.)", R"(Extended Axis: The difference between the command position of joint 3 and the encoder position of AC servo is out of range.)"} },
{ 473, {R"(부가축: 4번 관절의 지령 위치와 AC 서보의 엔코더 위치의 차이가 범위를 벗어납니다.)", R"(Extended Axis: The difference between the command position of joint 4 and the encoder position of AC servo is out of range.)"} },
{ 474, {R"(부가축: 5번 관절의 지령 위치와 AC 서보의 엔코더 위치의 차이가 범위를 벗어납니다.)", R"(Extended Axis: The difference between the command position of joint 5 and the encoder position of AC servo is out of range.)"} },
{ 475, {R"(부가축: 0번 관절의 AC 서보 드라이버에서 에러가 검출됩니다.)", R"(Extended Axis: An error is detected in the AC servo driver of joint 0.)"} },
{ 476, {R"(부가축: 1번 관절의 AC 서보 드라이버에서 에러가 검출됩니다.)", R"(Extended Axis: An error is detected in the AC servo driver of joint 1.)"} },
{ 477, {R"(부가축: 2번 관절의 AC 서보 드라이버에서 에러가 검출됩니다.)", R"(Extended Axis: An error is detected in the AC servo driver of joint 2.)"} },
{ 478, {R"(부가축: 3번 관절의 AC 서보 드라이버에서 에러가 검출됩니다.)", R"(Extended Axis: An error is detected in the AC servo driver of joint 3.)"} },
{ 479, {R"(부가축: 4번 관절의 AC 서보 드라이버에서 에러가 검출됩니다.)", R"(Extended Axis: An error is detected in the AC servo driver of joint 4.)"} },
{ 480, {R"(부가축: 5번 관절의 AC 서보 드라이버에서 에러가 검출됩니다.)", R"(Extended Axis: An error is detected in the AC servo driver of joint 5.)"} },
{ 481, {R"(선택된 디지털 출력 포트와 버퍼번호에서 이전 명령어 수행이 종료되지 않았습니다.)", R"(Execution of the previous command is not finished in the selected digital output port and buffer number.)"} },
{ 482, {R"(ProfiNet On 설정이 저장되었습니다. 설정을 반영하기 위해 시스템 전체 재부팅이 필요합니다.)", R"(ProfiNet On settings have been saved. A full system reboot is required for the settings to take effect.)"} },
{ 483, {R"(ProfiNet Off 설정이 저장되었습니다. 설정을 반영하기 위해 시스템 전체 재부팅이 필요합니다.)", R"(ProfiNet Off settings have been saved. A full system reboot is required for the settings to take effect.)"} },
{ 484, {R"(문자열과 같은 명칭의 Variable이 존재하지 않습니다.)", R"(Variable with the same name as a string does not exist.)"} },
{ 485, {R"(EMS 2 Safety 스위치로 인하여 로봇 팔의 전원이 차단되었습니다.)", R"(Robot arm has been powered off by the EMS 2 Safety switch.)"} },
{ 486, {R"(PRS Safety 스위치로 인하여 로봇 팔의 전원이 차단되었습니다.)", R"(Robot arm has been powered off by the PRS Safety switch.)"} },
{ 487, {R"(HSS Safety 스위치로 인하여 로봇 팔의 전원이 차단되었습니다.)", R"(Robot arm has been powered off by the HSS Safety switch.)"} },
{ 488, {R"(SSS Safety 스위치로 인하여 로봇 팔의 전원이 차단되었습니다.)", R"(Robot arm has been powered off by the SSS Safety switch.)"} },
{ 489, {R"(뮤직 인터페이스: 뮤직 재생에 필요한 드라이버가 설치되지 않았습니다.)", R"(Music Interface: The driver required to play music is not installed.)"} },
{ 490, {R"(긴급 모드 혹은 복구 모드로 로봇 팔이 활성화 되어 있습니다. 이 경우 프로그램을 재생할 수 없습니다.)", R"(The robot arm is activated in emergency mode or recovery mode. In this case, the program cannot be played.)"} },
{ 491, {R"(Tool 입출력에서는 해당 기능을 사용할 수 없습니다.)", R"(This function cannot be used in Tool I/O.)"} },
{ 492, {R"(IO보드 상태 데이터 수신 실패\nIO 보드 선 연결 상태를 확인하세요.\n24V io퓨즈가 나갔을 가능성이 있습니다.\n제어박스 24V SMPS가 손상되었을 수 있습니다.)", R"(Fail to get IO Board state data.\nCheck IO board cable connection state.\n24V IO Fuse may have been disconnected or broken.\nControl Box 24V SMPS may be damaged.)"} },
{ 493, {R"(동작 매크로: 코너 지점 중에 중복된 포인트가 존재합니다.)", R"(Motion macro: Identical points exist among corner points.)"} },
{ 494, {R"(동작 매크로: 간격 갯수는 1이상의 숫자를 입력해야 합니다.)", R"(Motion macro: For the number of intervals, a number greater than 1 must be entered.)"} },
{ 495, {R"(동작 매크로: 원호 피팅에 실패하였습니다. 설정 지점 정보가 올바른지 확인해주세요.)", R"(Motion macro: Arc fitting failed. Please check that the set point information is correct.)"} },
{ 496, {R"(Safety Plane 영역을 벗어납니다. 로봇 팔 동작이 제한됩니다.)", R"(It is out of the safety plane area. Robot arm motion is limited.)"} },
{ 497, {R"(로봇 팔의 관절 각도가 Safety Limit 범위를 벗어납니다. 로봇 팔 동작이 제한됩니다.)", R"(The joint angle of the robot arm is outside the Safety Limit range. Robot arm motion is limited.)"} },
{ 498, {R"(제어박스 내부의 CPU 온도가 높습니다. CPU 팬의 결합 상태 혹은 제어박스 메인 환풍 시스템에 문제가 없는지 확인하세요.)", R"(The CPU temperature inside the control box is high. Check if there is any problem with the CPU fan coupling or the control box main ventilation system.)"} },
{ 499, {R"(제어박스 내부의 마더보드 온도가 높습니다. 메인 환풍 시스템에 문제가 없는지 확인하세요.)", R"(The temperature of the motherboard inside the control box is high. Make sure there are no problems with the main ventilation system.)"} },
{ 500, {R"(설정된 속도 값이 너무 작은 값 입니다.)", R"(The set speed value is too small.)"} },
{ 501, {R"(설정된 가속도 값이 너무 작은 값 입니다.)", R"(The set acceleration value is too small.)"} },
{ 502, {R"(프로그램을 중간부터 실행하려면, 메인프로그램 영역 안에서 줄을 선택해야 합니다.)", R"(To run the program from the middle, you must select a line within the main program area.)"} },
{ 503, {R"(산술 연산 과정 중에 나누기 0이 존재하여 프로그램 운용을 중단합니다.)", R"(A divide by zero exists during an arithmetic operation, stopping program operation.)"} },
{ 504, {R"(시스템에 저장된 정보가 존재하지 않습니다.)", R"(Information stored in the system does not exist.)"} },
{ 505, {R"(Duplex 핀은 홀수 번호 핀에만 설정 가능합니다. 이전 번호의 핀과 연동되는 기능입니다.)", R"(Duplex pins can only be configured on odd-numbered pins. This function works with the pin of the previous number.)"} },
{ 506, {R"(IO 특수 기능에 정의된 포트는 Software PLC 용 포트에 지정 불가능 합니다.)", R"(The port defined in the IO special function cannot be assigned to the software PLC port.)"} },
{ 507, {R"(Software PLC 기능에 사용되는 포트는 IO 특수 기능으로 지정 불가능 합니다.)", R"(Ports used for Software PLC functions cannot be designated as IO special functions.)"} },
{ 508, {R"(IO 특수 기능이 저장되었습니다.\nSoftware PLC에서 동일한 입출력 포트를 사용하고 있다면 의도하지 않은 상황이 나타날 수 있으니 주의하세요.)", R"(The IO special function has been saved.\nIf the software PLC uses the same I/O port, be aware that unintended situations may occur.)"} },
{ 509, {R"(Software PLC 설정이 저장되었습니다.\nIO 특수 기능 설정에서 동일한 입출력 포트를 사용하고 있다면 의도하지 않은 상황이 나타날 수 있으니 주의하세요.)", R"(Software PLC settings have been saved.\nIf the same I/O port is used in the IO special function settings, be careful as unintended situations may occur.)"} },
{ 510, {R"(MUL 에러. 관절 0번의 각도가 무전원 상태에서 마지막 사용 값에서 90도 이상 움직였습니다. 손으로 브레이크를 해제해서 원래 사용하던 자세 근처로 관절을 돌려주세요. )", R"(MUL Error. The angle of joint 0 has moved more than 90 degrees from the last used value in the no-power state. Release the brake with your hand and return the joint to its original position.)"} },
{ 511, {R"(MUL 에러. 관절 1번의 각도가 무전원 상태에서 마지막 사용 값에서 90도 이상 움직였습니다. 손으로 브레이크를 해제해서 원래 사용하던 자세 근처로 관절을 돌려주세요. )", R"(MUL Error. The angle of joint 1 has moved more than 90 degrees from the last used value in the no-power state. Release the brake with your hand and return the joint to its original position.)"} },
{ 512, {R"(MUL 에러. 관절 2번의 각도가 무전원 상태에서 마지막 사용 값에서 90도 이상 움직였습니다. 손으로 브레이크를 해제해서 원래 사용하던 자세 근처로 관절을 돌려주세요. )", R"(MUL Error. The angle of joint 2 has moved more than 90 degrees from the last used value in the no-power state. Release the brake with your hand and return the joint to its original position.)"} },
{ 513, {R"(MUL 에러. 관절 3번의 각도가 무전원 상태에서 마지막 사용 값에서 90도 이상 움직였습니다. 손으로 브레이크를 해제해서 원래 사용하던 자세 근처로 관절을 돌려주세요. )", R"(MUL Error. The angle of joint 3 has moved more than 90 degrees from the last used value in the no-power state. Release the brake with your hand and return the joint to its original position.)"} },
{ 514, {R"(MUL 에러. 관절 4번의 각도가 무전원 상태에서 마지막 사용 값에서 90도 이상 움직였습니다. 손으로 브레이크를 해제해서 원래 사용하던 자세 근처로 관절을 돌려주세요. )", R"(MUL Error. The angle of joint 4 has moved more than 90 degrees from the last used value in the no-power state. Release the brake with your hand and return the joint to its original position.)"} },
{ 515, {R"(MUL 에러. 관절 5번의 각도가 무전원 상태에서 마지막 사용 값에서 90도 이상 움직였습니다. 손으로 브레이크를 해제해서 원래 사용하던 자세 근처로 관절을 돌려주세요. )", R"(MUL Error. The angle of joint 5 has moved more than 90 degrees from the last used value in the no-power state. Release the brake with your hand and return the joint to its original position.)"} },
{ 516, {R"(설정이 변경되었습니다. 제어 박스를 재부팅하세요.)", R"(Settings have been changed. Reboot the control box.)"} },
{ 517, {R"(AIDIN FT : 외부 F/T센서로 AIDIN AFT가 선택되었습니다.\n전체 시스템을 재부팅하세요.)", R"(AIDIN FT : AIDIN AFT is selected for the external F/T sensor.\nRe-boot all systems)"} },
{ 518, {R"(TCP IP 연결 방식을 위한 파일 전송 드라이버가 제어박스에 설치되어있지 않습니다.)", R"(The file transfer driver for the TCP IP connection method is not installed in the control box.)"} },
{ 519, {R"(모드버스 클라이언트 폴링 기능에서 지원 가능한 최대 변수 갯수를 넘었습니다.)", R"(The maximum number of variables supported by the Modbus client polling function has been exceeded.)"} },
{ 520, {R"(Safety 폴리곤 영역을 침범하였습니다. 로봇 팔 동작이 제한됩니다.)", R"(Safety polygon area has been violated. Robotic arm movements are limited.)"} },
{ 521, {R"(안전 폴리곤을 설정할 수 없습니다. 최소 3점 이상이 필요합니다. 폴리곤의 각 변은 겹치면 안됩니다.)", R"(Unable to set safety polygon. A minimum of 3 points is required. Each side of a polygon must not overlap.)"} },
{ 522, {R"(제어박스 내부 PC의 RAM 잔여량에 문제가 발생하였습니다. 시스템을 점검하세요.)", R"(There is a problem with the remaining RAM of the PC inside the control box. Check your system.)"} },
{ 523, {R"(제어박스 내부의 HDD 온도가 높습니다. 메인 환풍 시스템에 문제가 없는지 확인하세요.)", R"(The temperature of the HDD inside the control box is high. Make sure there are no problems with the main ventilation system.)"} },
{ 524, {R"(로봇 팔 관절 0 번에서 보호소자 FLT에러가 지속됩니다. 로봇 팔 운용에 문제가 생길 수 있습니다.)", R"(Protector FLT error persists at robot arm joint 0. Problems may arise when operating the robot arm.)"} },
{ 525, {R"(로봇 팔 관절 1 번에서 보호소자 FLT에러가 지속됩니다. 로봇 팔 운용에 문제가 생길 수 있습니다.)", R"(Protector FLT error persists at robot arm joint 1. Problems may arise when operating the robot arm.)"} },
{ 526, {R"(로봇 팔 관절 2 번에서 보호소자 FLT에러가 지속됩니다. 로봇 팔 운용에 문제가 생길 수 있습니다.)", R"(Protector FLT error persists at robot arm joint 2. Problems may arise when operating the robot arm.)"} },
{ 527, {R"(로봇 팔 관절 3 번에서 보호소자 FLT에러가 지속됩니다. 로봇 팔 운용에 문제가 생길 수 있습니다.)", R"(Protector FLT error persists at robot arm joint 3. Problems may arise when operating the robot arm.)"} },
{ 528, {R"(로봇 팔 관절 4 번에서 보호소자 FLT에러가 지속됩니다. 로봇 팔 운용에 문제가 생길 수 있습니다.)", R"(Protector FLT error persists at robot arm joint 4. Problems may arise when operating the robot arm.)"} },
{ 529, {R"(로봇 팔 관절 5 번에서 보호소자 FLT에러가 지속됩니다. 로봇 팔 운용에 문제가 생길 수 있습니다.)", R"(Protector FLT error persists at robot arm joint 5. Problems may arise when operating the robot arm.)"} },
{ 530, {R"(Fitting: 입력 점의 갯수는 3개 이상 이어야 합니다.)", R"(Fitting: The number of input points must be 3 or more.)"} },
{ 531, {R"(Fitting: 레퍼런스 포인트 갯수와 데이터 포인트 갯수가 다릅니다.)", R"(Fitting: The number of reference points and the number of data points are different.)"} },
{ 532, {R"(Fitting: 이 기능을 실행할 수 없는 상태 입니다.)", R"(Fitting: This function cannot be performed.)"} },
{ 533, {R"(Fitting: 수치 계산 과정에서 문제가 발생하였습니다.)", R"(Fitting: A problem occurred during numerical calculation.)"} },
{ 534, {R"(Fitting: 계산된 결과가 허용된 오차 범위를 초과합니다.)", R"(Fitting: The calculated result exceeds the allowed error range.)"} },
{ 535, {R"(Fitting: 너무 가까운 점이 존재합니다.)", R"(Fitting: There are points that are too close.)"} },
{ 536, {R"(Fitting: 계산에 사용되는 점이 일직선 상에 존재합니다.)", R"(Fitting: The points used in the calculation lie on a straight line.)"} },
{ 537, {R"(Fitting: 계산에 실패하였습니다.)", R"(Fitting: Calculation failed.)"} },
{ 538, {R"(Fitting: 동작 중에는 이 기능을 실행할 수 없습니다.)", R"(Fitting: This function cannot be performed during operation.)"} },
{ 539, {R"(Fitting: 레퍼런스 포인트와 데이터 포인트의 점 간격 차이가 기준을 넘어섭니다.)", R"(Fitting: The point spacing difference between the reference point and the data point exceeds the standard.)"} },
{ 540, {R"(통신에러 : 로봇 팔의 관절 0번 통신이 불안정합니다. L2C 통신라인이 불안정 합니다.)", R"(Communication error: The communication of joint 0 of the robot arm is unstable. L2C communication line is unstable.)"} },
{ 541, {R"(통신에러 : 로봇 팔의 관절 1번 통신이 불안정합니다.  L2C 통신라인이 불안정 합니다.)", R"(Communication error: The communication of joint 1 of the robot arm is unstable. L2C communication line is unstable.)"} },
{ 542, {R"(통신에러 : 로봇 팔의 관절 2번 통신이 불안정합니다.  L2C 통신라인이 불안정 합니다.)", R"(Communication error: The communication of joint 2 of the robot arm is unstable. L2C communication line is unstable.)"} },
{ 543, {R"(통신에러 : 로봇 팔의 관절 3번 통신이 불안정합니다.  L2C 통신라인이 불안정 합니다.)", R"(Communication error: The communication of joint 3 of the robot arm is unstable. L2C communication line is unstable.)"} },
{ 544, {R"(통신에러 : 로봇 팔의 관절 4번 통신이 불안정합니다.  L2C 통신라인이 불안정 합니다.)", R"(Communication error: The communication of joint 4 of the robot arm is unstable. L2C communication line is unstable.)"} },
{ 545, {R"(통신에러 : 로봇 팔의 관절 5번 통신이 불안정합니다.  L2C 통신라인이 불안정 합니다.)", R"(Communication error: The communication of joint 5 of the robot arm is unstable. L2C communication line is unstable.)"} },
{ 546, {R"(통신에러 : 로봇 팔의 툴플랜지 통신이 불안정합니다.  L2C 통신라인이 불안정 합니다.)", R"(Communication error: The communication of tool flange of the robot arm is unstable. L2C communication line is unstable.)"} },
{ 547, {R"(L2C 통신라인 불안정으로 인한 IO보드 상태 데이터 수신 실패.)", R"(Failure to receive IO board status data due to L2C communication line instability.)"} },
{ 548, {R"(그리퍼 초기화 과정이 시간초과되었습니다. 그리퍼로부터 정상적인 데이터를 수신하지 못하였습니다.)", R"(The gripper initialization process timed out. No normal data was received from the gripper.)"} },
{ 549, {R"(관절 보호 에러 : Motor Stator Temperature Error at Joint 0)", R"(Joint Protection Error : Motor Stator Temperature Error at Joint 0)"} },
{ 550, {R"(관절 보호 에러 : Motor Stator Temperature Error at Joint 1)", R"(Joint Protection Error : Motor Stator Temperature Error at Joint 1)"} },
{ 551, {R"(관절 보호 에러 : Motor Stator Temperature Error at Joint 2)", R"(Joint Protection Error : Motor Stator Temperature Error at Joint 2)"} },
{ 552, {R"(관절 보호 에러 : Motor Stator Temperature Error at Joint 3)", R"(Joint Protection Error : Motor Stator Temperature Error at Joint 3)"} },
{ 553, {R"(관절 보호 에러 : Motor Stator Temperature Error at Joint 4)", R"(Joint Protection Error : Motor Stator Temperature Error at Joint 4)"} },
{ 554, {R"(관절 보호 에러 : Motor Stator Temperature Error at Joint 5)", R"(Joint Protection Error : Motor Stator Temperature Error at Joint 5)"} },
{ 555, {R"(관절 보호 에러 : Current Sensing Biasing Error at Joint 0)", R"(Joint Protection Error : Current Sensing Biasing Error at Joint 0)"} },
{ 556, {R"(관절 보호 에러 : Current Sensing Biasing Error at Joint 1)", R"(Joint Protection Error : Current Sensing Biasing Error at Joint 1)"} },
{ 557, {R"(관절 보호 에러 : Current Sensing Biasing Error at Joint 2)", R"(Joint Protection Error : Current Sensing Biasing Error at Joint 2)"} },
{ 558, {R"(관절 보호 에러 : Current Sensing Biasing Error at Joint 3)", R"(Joint Protection Error : Current Sensing Biasing Error at Joint 3)"} },
{ 559, {R"(관절 보호 에러 : Current Sensing Biasing Error at Joint 4)", R"(Joint Protection Error : Current Sensing Biasing Error at Joint 4)"} },
{ 560, {R"(관절 보호 에러 : Current Sensing Biasing Error at Joint 5)", R"(Joint Protection Error : Current Sensing Biasing Error at Joint 5)"} },
{ 561, {R"(이전 동작이 종료되지 않은 시점에서 새로운 동작 명령이 수신되었습니다.)", R"(A new operation command was received at a point where the previous operation had not yet concluded.)"} },
{ 562, {R"(목표 자세의 관절 각도가 제한 범위를 벗어납니다.)", R"(Joint angle of the target posture exceeds the specified range.)"} },
{ 563, {R"(목표 지점의 XYZ 위치값이 제한 범위를 벗어납니다.)", R"(XYZ position of the target point is beyond the specified range.)"} },
{ 564, {R"(이 기능을 사용하기 위해서는 고 해상도 ADC 모드가 설정되어 있어야합니다.)", R"(To utilize this feature, the high-resolution ADC mode must be configured.)"} },
{ 565, {R"(정의되지 않은 모델 코드 번호 입니다. 번호를 확인하거나 제어박스 소프트웨어를 최신으로 업데이트하세요.)", R"(Undefined model code number. Check the number or update the control box software to the latest.)"} },
{ 566, {R"(동작 속도 프로파일 생성 실패. 목표 속도를 줄이거나 목표 가속도를 높여주세요.)", R"(Failed to create motion speed profile. Please reduce the target speed or increase the target acceleration.)"} },
{ 567, {R"(제어박스의 전원부 계통의 예측온도가 임계값을 벗어납니다.)", R"(The predicted temperature of the power system of the control box is outside the threshold.)"} },
{ 568, {R"(입력된 Servo J 파라미터가 사용 가능 범위를 벗어납니다.)", R"(The Servo J parameters entered are outside the available range.)"} },
{ 569, {R"(입력된 Servo L 파라미터가 사용 가능 범위를 벗어납니다.)", R"(The Servo L parameters entered are outside the available range.)"} },
{ 570, {R"(입력된 Servo T 파라미터가 사용 가능 범위를 벗어납니다.)", R"(The Servo T parameters entered are outside the available range.)"} },
{ 571, {R"(충돌 감지 동작 모드 : 0.8 초 동안 관절 토크를 풀어주는 모드)", R"(Collision detection motion setting : Mode to release joint torque for 0.8 seconds)"} },
{ 572, {R"(충돌 감지 동작 모드 : 1.6 초 동안 관절 토크를 풀어주는 모드)", R"(Collision detection motion setting : Mode to release joint torque for 1.6 seconds)"} },
{ 573, {R"(원 동작을 위한 중심 축 설정 값이 올바르지 않습니다.)", R"(The central axis settings for circular motion are incorrect.)"} },
{ 574, {R"(원 동작을 위해 설정된 점들이 너무 가깝습니다. 원 궤적을 생성하지 못합니다.)", R"(The points set for circular motion are too close. A circular trajectory cannot be created.)"} },
{ 575, {R"(궤적 생성 단계에서 수치적인 문제가 발생합니다.)", R"(Numerical problems arise during the trajectory generation stage.)"} },
{ 576, {R"(특정 점들이 일직선 상에 존재하기 때문에 원하는 궤적 생성이 불가능합니다.)", R"(Because certain points exist on a straight line, it is impossible to create the desired trajectory.)"} },
{ 577, {R"(최소 2개 이상의 지점이 설정되어야 해당 동작을 수행할 수 있습니다.)", R"(At least two points must be set to perform the motion.)"} },
{ 578, {R"(설정된 모드 버스 ID 가 사용 가능한 범위를 벗어납니다.)", R"(The set Modbus ID is outside the available range.)"} },
{ 579, {R"(입력된 소켓 번호가 사용가능한 핸들러 범위를 벗어납니다.)", R"(The socket number entered is outside the range of available handlers.)"} },
{ 580, {R"(데이터 테이블이 전송되었습니다.)", R"(The data table has been sent.)"} },
{ 581, {R"(데이터 테이블이 저장되었습니다.)", R"(The data table has been saved.)"} },
{ 582, {R"(시리얼 번호가 저장되었습니다.)", R"(The serial number has been saved.)"} },
{ 583, {R"(시리얼 번호를 저장하지 못하였습니다.)", R"(Failed to save serial number.)"} },
{ 584, {R"(ID 설정 명령이 전송되었습니다. 전체 시스템을 재부팅하세요.)", R"(An ID setting command has been sent. Reboot the entire system.)"} },
{ 585, {R"(선택된 드라이버가 전송되었습니다. 설치 과정을 진행하세요.)", R"(The selected drivers have been transferred. Proceed with the installation process.)"} },
{ 586, {R"(선택된 드라이버 설치가 완료되었습니다. 전체 시스템을 재부팅하세요.)", R"(Installation of the selected driver is complete. Reboot the entire system.)"} },
{ 587, {R"(부가축: 캘리브레이션 연산 과정에서 수학적 문제가 발생합니다. 입력된 자세 정보를 확인하세요.)", R"(External Axis: A mathematical problem arises during the calibration calculation process. Check the entered posture information.)"} },
{ 588, {R"(입력된 IP 주소가 사용가능한 범위가 아닙니다.)", R"(The IP address entered is not in an available range.)"} },
{ 589, {R"(이 기능은 Real Robot 모드에서만 사용 가능합니다.)", R"(This feature is only available in Real Robot mode.)"} },
{ 590, {R"(제어박스 시간대 영역이 설정되었습니다.)", R"(The control box time zone has been set.)"} },
{ 591, {R"(제어박스 시간대 영역 설정에 부적합한 값이 입력되었습니다.)", R"(An inappropriate value was entered in the control box time zone setting.)"} },
{ 592, {R"(명령어가 수행되었습니다. 제어박스가 몇 초 안에 자동으로 재부팅 됩니다.)", R"(The command has been executed. The control box will automatically reboot within a few seconds.)"} },
{ 593, {R"(Modbus ASCII 쓰기 과정에서 시간 초과가 발생하였습니다.)", R"(A timeout occurred during the Modbus ASCII writing process.)"} },
{ 594, {R"(Modbus ASCII 쓰기 과정에서 정상적인 ACK 신호를 수신하지 못하였습니다.)", R"(A normal ACK signal was not received during the Modbus ASCII writing process.)"} },
{ 595, {R"(Modbus ASCII 쓰기 과정에서 버스 에러가 발생하였습니다.)", R"(A bus error occurred during the Modbus ASCII writing process.)"} },
{ 596, {R"(Modbus ASCII 읽기 과정에서 시간 초과가 발생하였습니다.)", R"(A timeout occurred during the Modbus ASCII reading process.)"} },
{ 597, {R"(Modbus ASCII 읽기 과정에서 정상적인 ACK 신호를 수신하지 못하였습니다.)", R"(A normal ACK signal was not received during the Modbus ASCII reading process.)"} },
{ 598, {R"(Modbus ASCII 읽기 과정에서 버스 에러가 발생하였습니다.)", R"(A bus error occurred during the Modbus ASCII reading process.)"} },
{ 599, {R"(Modbus ASCII 읽기 과정에서 포멧 에러가 발생하였습니다.)", R"(A format error occurred during the Modbus ASCII reading process.)"} },
{ 600, {R"(관절 감속기 보호 에러 0: 기어의 허용 토크 이상의 부하가 발생됩니다.)", R"(Joint reducer protection error 0: A load exceeding the allowable torque of the gear occurs.)"} },
{ 601, {R"(관절 감속기 보호 에러 1: 기어의 허용 토크 이상의 부하가 발생됩니다.)", R"(Joint reducer protection error 1: A load exceeding the allowable torque of the gear occurs.)"} },
{ 602, {R"(관절 감속기 보호 에러 2: 기어의 허용 토크 이상의 부하가 발생됩니다.)", R"(Joint reducer protection error 2: A load exceeding the allowable torque of the gear occurs.)"} },
{ 603, {R"(관절 감속기 보호 에러 3: 기어의 허용 토크 이상의 부하가 발생됩니다.)", R"(Joint reducer protection error 3: A load exceeding the allowable torque of the gear occurs.)"} },
{ 604, {R"(관절 감속기 보호 에러 4: 기어의 허용 토크 이상의 부하가 발생됩니다.)", R"(Joint reducer protection error 4: A load exceeding the allowable torque of the gear occurs.)"} },
{ 605, {R"(관절 감속기 보호 에러 5: 기어의 허용 토크 이상의 부하가 발생됩니다.)", R"(Joint reducer protection error 5: A load exceeding the allowable torque of the gear occurs.)"} }
};

}  // namespace rb::podo